export const palavrasPT = [
  "3D", "Abacaxi", "Abdômen", "Abelha", "Aberto", "Abismo", "Abóbora", "Abobrinha", "Absinto", "Absorvente",
  "Abuja", "Academia", "Açaí", "Ação", "Acaso", "Ace", "Aceitação", "Acer", "Acetona",
  "Aço", "Acorde", "Acordeão", "Açougueiro", "Acrílica", "Acrofobia", "Açúcar", "Açude", "Adaga", "Adamantium",
  "Adega", "Ades", "Adesivo", "Adidas", "Adis Abeba", "Administrador", "Admiração", "Adoção", "Advogado", "Aeroporto",
  "Afeganistão", "Afeto", "Afilhada", "Afilhado", "África do Sul", "Afrodite", "Ágata", "Agenda", "Agogô", "Agorafobia",
  "Agridoce", "Água", "Águia", "Airfryer", "Ajax", "Akita", "Albânia", "Albergue", "Albert Einstein",
  "Álbum", "Alce", "Alcorão", "Aldeia", "Alecrim", "Alegria", "Alemanha", "Alemão", "Alergia", "Alexa",
  "Alexandre o Grande", "Alfa Romeo", "Alface", "Alga", "Álgebra", "Algodão", "Algoritmo", "Alho", "Ali", "Aliado",
  "Aliança", "Alicate", "Alívio", "Alma", "Almofada", "Almoxarifado", "Alpinismo", "Alquimia", "Altar", "Alto",
  "Altruísta", "Altura", "Alumínio", "Alvo", "Amã", "Amaciante", "Amante", "Amarelinha", "Amarelo", "Amargo",
  "Amassado", "Amazon", "Âmbar", "Ambulância", "AMD", "Amêndoa", "Amendoim", "Ametista", "Amígdala", "Amizade",
  "Amor", "Amsterdã", "Amuleto", "Analista", "Anão", "Ancara", "Anchova", "Ancinho", "Andorinha", "Andorra",
  "Anel", "Anelar", "Anêmona", "Anfitrião", "Angola", "Angorá", "Anil", "Animação", "Animador", "Anitta",
  "Aniversário", "Anjo", "Ano Novo", "Ansiedade", "Ansioso", "Antebraço", "Antena", "Antessala", "Antigo", "Antílope",
  "Aorta", "Apagador", "Aparelho", "Apartamento", "Apatia", "Apego", "Apêndice", "Aplausos", "Aplicativo", "Apocalipse",
  "Apolo", "Apontador", "Aposentadoria", "Apple", "Aprendiz", "Aprisco", "Aquaman", "Aquarela", "Aquário", "aquático",
  "Aquecedor", "Aquiles", "Arábia Saudita", "Aracaju", "Aracnofobia", "Arado", "Aragorn", "Arame", "Aranha", "Arcanjo",
  "Arco", "Ardósia", "Área", "Areia", "Arena", "Arenque", "Ares", "Argamassa", "Argel", "Argélia",
  "Argentina", "Argila", "Argola", "Argônio", "Áries", "Armadura", "Armani", "Armário", "Armazém", "Armênia",
  "Aromatizador", "Arquibancada", "Arquipélago", "Arquiteto", "Arquivo", "Arraia", "Arremesso", "Arrependimento", "Arroz", "Arruda",
  "Arsenal", "Artefato", "Ártemis", "Artéria", "Artesanato", "Articulação", "artificial", "Árvore", "Ás", "Asa",
  "Ascendente", "Asfalto", "Ash", "Asma", "Áspero", "Aspirador", "Assento", "Assistente", "Assombração", "Assunção",
  "Asteroide", "Aston Martin", "Astral", "Astronomia", "Asus", "Atabaque", "Ateliê", "Atena", "Atenas", "Atendente",
  "Athletico Paranaense", "Atirador", "Atlético de Madrid", "Atlético Mineiro", "Atletismo", "Átomo", "Ator", "Atriz", "Atualização", "Atum",
  "Auckland", "Audi", "Auditor", "Audrey Hepburn", "Aura", "Aurora", "Austrália", "Áustria", "Automação", "Automóvel",
  "Autorama", "Avaí", "Avalanche", "Avaliador", "Avarento", "Aveia", "Avenida", "Avental", "Aventura", "Avião",
  "aviões", "Avó", "Avô", "Avon", "Axé", "Axila", "Azaleia", "Azar", "Azedo", "Azeite",
  "Azerbaijão", "Azul", "Azulejo", "Babosa", "Babyliss", "Bacalhau", "Bach", "Bacia", "Backup", "Baço",
  "Bacon", "Bactéria", "Badejo", "Badminton", "Bagdá", "Bagunçado", "Bahamas", "Bahia", "Bahrein", "Baiacu",
  "Bairro", "Baixo", "Balada", "Balão", "Balconista", "Balde", "Baleia", "Ballet", "Balsa", "Bamba",
  "Bambolê", "Bambu", "Banana", "Bancário", "Banco", "Banco do Brasil", "Banda", "Bandolim", "Bangkok", "Bangladesh",
  "Banheira", "Banheiro", "Banjo", "Bar", "barba", "Barbados", "Bárbaro", "Barbeador", "Barbear", "Barbie",
  "Barca", "Barcelona", "Barco", "Bardo", "Barney", "Barra", "Barragem", "Barriga", "Bart", "Bartender",
  "basquete", "Basquete", "Basset", "Bastão", "Batata", "Batedeira", "Bateria", "Batida", "Batizado", "Batman",
  "Bayern de Munique", "Beagle", "Bebê", "Beethoven", "Bege", "Begônia", "Beijinho", "Beirute", "Beisebol", "Belém",
  "Bélgica", "Belize", "Belo Horizonte", "Belzebu", "Bem", "Benfica", "Bengal", "Benin", "Bentley", "Berílio",
  "Berimbau", "Berinjela", "Berlim", "Bermuda", "Berna", "Bernardo", "Berrante", "Besouro", "Betoneira", "Bexiga",
  "Beyoncé", "Bíblia", "Biblioteca", "Bicho", "Bicicleta", "bico", "Biden", "Bielorrússia", "Big Bang", "bike",
  "Bila", "Bilheteria", "Bílis", "Bill Gates", "Bimotor", "Biologia", "Bioma", "Bipe", "Biplano", "Biquíni",
  "Bisão", "Bisavó", "Bisavô", "Biscoito", "Bisneta", "Bisneto", "Bitcoin", "Blazer", "Bloco", "Blog",
  "Blu-ray", "Blues", "Bluetooth", "Blusa", "BMW", "Boa Vista", "Bob Esponja", "Boca", "Boca Juniors", "Bocha",
  "Bochecha", "Bogotá", "Bola", "Bolero", "Boleto", "Boliche", "Bolívia", "Bolo", "Bolsa", "Bolso",
  "Bolsonaro", "Bomba", "Bombaim", "Bombeiro", "Bombom", "Bombril", "Bonde", "Bondoso", "Boné", "Boneca",
  "Boneco", "Bonito", "Bonsai", "Borboleta", "Bordado", "Border", "Bordô", "Boreal", "Boro", "borracha",
  "Borracha", "Borussia Dortmund", "Bósnia", "Bosque", "Bossa Nova", "Bota", "Botafogo", "Botão", "Boticário", "Botsuana",
  "Bowser", "Box", "Boxe", "Boxer", "Braço", "Bradesco", "Branca", "Branco", "Brasil", "Brasileirão",
  "Brasília", "Brazzaville", "break", "Brejo", "Brigadeiro", "Brinco", "Brisa", "Brita", "Britadeira", "Brócolis",
  "Bromélia", "Bronquite", "Bronze", "Brunei", "Bruxelas", "Bucha", "Buda", "Budapeste", "Buenos Aires", "Búfalo",
  "Bugatti", "Bulgária", "Bulldog", "Bulls", "Buraco", "Burger King", "Burkina Faso", "burro", "Burro", "Burundi",
  "Butão", "Buzina", "C&A", "cabeça", "Cabeça", "Cabelo", "Cabo", "Cabo Verde", "Cabresto", "Cabul",
  "Caçarola", "Cachaça", "Cachecol", "Cacheta", "Cachoeira", "Cachorro", "Cacto", "Cadarço", "Cadeira", "Cadente",
  "Caderno", "Café", "Cafeteira", "Caiaque", "Caipira", "Caipirinha", "Cairo", "Caixa", "Cajado", "Cajuzinho",
  "Cal", "calça", "Calça", "Calcanhar", "Calcinha", "Cálcio", "Calculadora", "Cálculo", "Caldeira", "Caldo",
  "Caleidoscópio", "Calendário", "Caligrafia", "Calma", "Calmo", "Calvin Klein", "Cama", "Câmara", "Camarão", "Camarim",
  "Camarões", "Camberra", "Camboja", "Camelo", "Câmera", "Caminhada", "Caminhão", "Caminhoneiro", "Caminhonete", "Camisa",
  "Camiseta", "Camomila", "Campinas", "Camping", "campo", "Campo", "Campo Grande", "Camurça", "cana", "Canadá",
  "Canção", "Câncer", "Canela", "Caneleira", "Caneta", "Canetão", "Canetinha", "Canguru", "Canhão", "Canino",
  "Canivete", "Canjica", "Canoa", "Canon", "Canson", "Canto", "Cantor", "Cantora", "Caos", "Capacete",
  "Capela", "Capital", "Capitão", "Capitão América", "Cappuccino", "Capricórnio", "Capuz", "Cáqui", "cara", "Cara",
  "Caracas", "Caracol", "Caramelo", "Caranguejo", "Caratê", "Carbono", "cargueiro", "Cárie", "Carimbo", "Carinho",
  "Carlos Drummond", "Carmesim", "Carnaval", "Carne", "Carolina", "Carpaccio", "Carpinteiro", "Carregador", "Carrinho", "Carro",
  "Carroça", "Carta", "Cartão", "Cartas", "Carteira", "Carteiro", "Cartilagem", "Cartola", "Cartolina", "Cartório",
  "Cartum", "Carvão", "Casa", "Casablanca", "Casaco", "Casal", "Casamento", "Casca", "Cassete", "Castanha",
  "Castelo", "Catar", "Catavento", "Catedral", "Cavala", "Cavalete", "Cavalo", "Cavaquinho", "Caviar", "Cazaquistão",
  "CD", "Ceará", "Cebola", "Cebolinha", "Celeiro", "Celtics", "Célula", "Celular", "Cemitério", "Cena",
  "Cenoura", "Centauro", "Central", "Centro", "Cera", "Cerâmica", "Cerca", "Cereal", "Cérebro", "Cerveja",
  "Cesta", "Cesto", "Ceticismo", "Cetim", "Céu", "Ceviche", "Chá", "Chácara", "Chade", "Chakra",
  "Chaleira", "Chama", "Champanhe", "Champions League", "Chanel", "Chapecoense", "Chapéu", "Chapinha", "Charlie Chaplin", "Charrete",
  "Chatbot", "Chave", "Che Guevara", "Cheese", "Chef", "Chefe", "Cheio", "Chelsea", "Cheque", "Chevrolet",
  "Chicago", "Chicote", "Chihuahua", "Chile", "Chimarrão", "Chimpanzé", "China", "Chinelo", "Chipre", "Chiqueiro",
  "Chocolate", "Chocotone", "Chopp", "Choque", "Chow", "Chumbo", "Chun-Li", "Churchill", "Churrasco", "Churros",
  "chuva", "Chuva", "Chuveiro", "Ciano", "Cicatriz", "Ciclismo", "Ciclone", "Ciclope", "Cidade", "Cidadela",
  "Cidra", "Científica", "Cientista", "Cílios", "Cimento", "Cinema", "Cingapura", "Cinto", "Cintura", "Cinturão",
  "Cinza", "Circo", "Circuito", "circular", "Cisne", "Citrino", "Ciúme", "Clareza", "Clarice Lispector", "Clarinete",
  "claro", "Claro", "Clássica", "Claustrofobia", "Clavícula", "Cleópatra", "Clérigo", "Cliente", "Clínica", "Clips",
  "Cloro", "Closet", "CNC", "Coalhada", "Cobertor", "Cobra", "Cobre", "Coca-Cola", "Cocada", "Cóccix",
  "Cocheira", "Cocker", "coco", "Codificação", "Código", "Codorna", "Coelhinho da Páscoa", "Coelho", "Coentro", "Cofre",
  "Cogumelo", "Cola", "Colada", "Colagem", "Colapso", "Colar", "Colecionismo", "Colega", "Colégio", "Colesterol",
  "Colete", "Coletor", "Colgate", "Colheitadeira", "Colher", "Colina", "Collie", "Colômbia", "Colônia", "Coluna",
  "com", "Comadre", "Comandante", "Começo", "Comédia", "Comentário", "Comerciante", "Cometa", "Comores", "Compadre",
  "Compaixão", "Companheira", "Companheiro", "Compartilhamento", "Compasso", "Compensado", "Competição", "Composição", "Compositor", "Comprador",
  "Compreensão", "Compressor", "Comprimido", "Computador", "Concerto", "Concreto", "Condenação", "Condensado", "Condicionador", "Condutor",
  "Conexão", "Confeitaria", "Confeiteiro", "Confiança", "Conflito", "Conforto", "Confusão", "Congo", "Conhaque", "Conhecido",
  "Consciência", "Consequência", "Console", "Consultor", "Contador", "Continente", "Contorcionista", "Contrabaixo", "Contrato", "Controlador",
  "Controle", "Conversível", "Convidado", "Convívio", "Coon", "Cooperação", "Copa", "Copa do Mundo", "Copas", "Copenhague",
  "Copo", "Coquetel", "Cor", "Coração", "Coragem", "Corajoso", "Coral", "Corda", "Cordão", "Coreia do Norte",
  "Coreia do Sul", "Coringa", "Corinthians", "Coritiba", "Córnea", "Corneta", "Coroa", "Corredor", "Córrego", "Correio",
  "Corretivo", "Corretor", "corrida", "Corrida", "Cortador", "corte", "Corte", "Cortina", "Coruja", "Corvo",
  "Cosmopolitan", "Costa", "Costa do Marfim", "Costa Rica", "Costas", "Costela", "Costura", "Cotonete", "Cotoveleira", "Cotovelo",
  "Coturno", "Country", "Couro", "Couve", "Covardia", "Cowboys", "Coxa", "Cozinha", "Cozinheiro", "Crachá",
  "Cratera", "Cravo", "Cream", "Crédito", "Creme", "Crepe", "Crepom", "Criação", "Criativo", "Criptografia",
  "Criptomoeda", "Críquete", "Cristais", "Cristal", "Cristiano Ronaldo", "Croácia", "Crochê", "Crocodilo", "Crossover", "Cruel",
  "Crush", "Cruzamento", "Cruzeiro", "Cuba", "Cubo", "Cueca", "Cuiabá", "Cuidado", "Culinária", "Culpa",
  "Cultivo", "Cúmplice", "Cunhada", "Cunhado", "Cupuaçu", "Curativo", "Curau", "Curiosidade", "Curitiba", "Curral",
  "Curta", "da", "Daca", "Dacar", "Dachshund", "Dado", "dados", "Dalai Lama", "Dálmata", "Dama",
  "Damas", "Damasco", "Dança", "Danificado", "Dante Alighieri", "Darth Vader", "Datilografar", "DC", "de", "De",
  "Débito", "Decepção", "Decote", "Dedão", "Dedo", "Defensor", "Delegacia", "Delegado", "Délhi", "Dell",
  "delta", "Delta", "Demônio", "Denso", "Dental", "Dente", "Dentes", "Dentista", "Depósito", "Deprimido",
  "Derme", "Desânimo", "Descarga", "Desconfiança", "Desconforto", "Desejo", "Desenho", "Desenvolvedor", "Deserto", "Desespero",
  "Designer", "Desinfetante", "Deslizamento", "Desodorante", "Despacho", "Despensa", "Destino", "Destrancado", "Destruição", "Detergente",
  "Determinação", "Detetive", "Dethrone", "Dever", "Dharma", "Dia", "Dia das Mães", "Dia dos Namorados", "Dia dos Pais", "Diabetes",
  "Diafragma", "Diamante", "Dimensão", "Dinamarca", "Dinheiro", "Dior", "Diova", "Dique", "Direito", "Diretor",
  "Dirigível", "Discman", "discos", "Disney", "Dispositivo", "Disquete", "Distanciamento", "Distribuidor", "Distrito", "Dívida",
  "Divórcio", "Djibouti", "DNA", "do", "Doberman", "Dobrado", "Dobradura", "Doce", "Documentário", "Documento",
  "Dodgers", "Doente", "Dojô", "Dólar", "Dom Pedro", "Domador", "Dominica", "Dominó", "Doninha", "Dor",
  "Dormitório", "Dorso", "Dourado", "Dove", "Download", "Drácula", "Dragão", "Drama", "Drive", "Drone",
  "Druida", "Dubai", "Dublê", "Dublin", "Ducati", "Dumbledore", "Dungeon", "Dunk", "Dupla", "Durex",
  "duro", "Duro", "Dúvida", "DVD", "Eclair", "Eclipse", "Eco", "Economista", "Ecossistema", "Edição",
  "Edifício", "Educador", "Efêmero", "Egito", "Ego", "Egoísta", "El Salvador", "Elastano", "Elástica", "Elástico",
  "Elefante", "elétrica", "Eletricista", "elétrico", "Elétron", "Eletrônica", "Elevador", "Elfo", "Elixir", "Elon Musk",
  "Elvis Presley", "em", "Email", "Emirados Árabes", "Emmy", "Emoji", "Empate", "Empatia", "Empilhadeira", "Empregado",
  "Empresa", "Empréstimo", "Encanador", "Encanto", "Encharcado", "Enchente", "Energia", "Enfermeiro", "Enferrujado", "Engenheiro",
  "Engolidor", "Enguia", "Enteada", "Enteado", "Entrada", "Entregador", "Entusiasmo", "Envelope", "Enxada", "Enxaguante",
  "Enxaqueca", "Enxofre", "Epiderme", "Equador", "Equilíbrio", "Equilibrista", "Equipamento", "Eritreia", "Erupção", "Ervilha",
  "Escada", "Escala", "Escalada", "Escama", "Escápula", "Escarlate", "Escavadeira", "Escola", "Escolha", "Escorpião",
  "Escorredor", "Escova", "Escrita", "Escritório", "Escrivão", "Escudo", "Escultura", "Escuna", "escuro", "Escuro",
  "Esgrima", "Eslováquia", "Eslovênia", "Esmalte", "Esmeralda", "Esôfago", "espacial", "Espaçonave", "espada", "Espada",
  "Espadas", "Espanador", "Espanha", "Espantalho", "Espátula", "Espectro", "Espelho", "Esperança", "Esperto", "Espetáculo",
  "Espinafre", "Espiritismo", "Espírito", "espirra", "Esponja", "Esportivo", "Esposa", "Espremedor", "Espuma", "Espumante",
  "Esquadro", "Esqueleto", "Esqui", "Esquilo", "Essência", "Estábulo", "Estação", "Estacionamento", "Estádio", "Estado",
  "Estados Unidos", "Estadual", "Estanho", "Estante", "estar", "Estatística", "Estável", "Esteira", "Esterno", "Estiagem",
  "Estilete", "Estilingue", "Estocolmo", "Estômago", "Estônia", "Estrada", "Estranho", "Estreia", "Estrela", "Estressado",
  "Estuário", "Estúdio", "Éter", "Eternidade", "Ethereum", "Ética", "Etiópia", "Etiqueta", "Eucalipto", "Euforia",
  "Eufórico", "Euro", "Evolução", "Ex", "Exaustão", "Excentricidade", "Existência", "Exposição", "Expresso", "Externo",
  "Extrator", "Extrovertido", "Fábrica", "Faca", "Facão", "Facas", "Face", "Facebook", "Fada", "Fada do Dente",
  "Faixa", "falante", "Falcão", "Falso", "Família", "Fantasia", "Fantasma", "Fantoche", "Farda", "Farinha",
  "Farmacêutico", "Farmácia", "Faroeste", "Farpado", "Fascínio", "Faustão", "Fax", "Fazenda", "Fé", "Febre",
  "Fechado", "Fechadura", "Feijão", "Feio", "Feira", "Feiticeiro", "Feitiço", "Feliz", "Fêmur", "fenda",
  "Fênix", "Feriado", "Férias", "Ferida", "Fernando Pessoa", "Ferradura", "Ferramenta", "Ferrari", "Ferro", "Ferrorama",
  "Ferrugem", "Festa", "Festival", "Fiat", "Fibra", "Fíbula", "Ficção", "Ficha", "Fichário", "Fidel Castro",
  "Fígado", "Figueirense", "Fiji", "Filha", "Filho", "Filiação", "Filipinas", "Filmagem", "Filósofo", "Filtro",
  "Fim", "Finalização", "Financeiro", "Financiamento", "Finlândia", "Fio", "Firewall", "Fiscal", "Física", "Fisioterapeuta",
  "fita", "Fita", "Fivela", "Fixo", "Flamenco", "Flamengo", "Flanela", "Flash", "Flauta", "Flautim",
  "Flecha", "Flexível", "Flor", "Floresta", "Florianópolis", "Fluminense", "Flúor", "Fobia", "Foca", "Fogão",
  "Fogueira", "Foguete", "Foice", "Folha", "Folículo", "Folk", "Fone", "Ford", "Formão", "Formatura",
  "Formiga", "Fornecedor", "Forno", "Forró", "Fortaleza", "Forte", "Fósforo", "Fotografia", "Fraco", "Frágil",
  "Fralda", "França", "Franco", "Frango", "Frankenstein", "Fratura", "Fred", "Freezer", "Fresadora", "Fresco",
  "Freya", "Frigideira", "Frio", "Frodo", "Fronteira", "Frustração", "Frutas", "Fúcsia", "Fungo", "Funicular",
  "Funk", "Furacão", "Furadeira", "futebol", "Futebol", "Futsal", "Gabão", "Gabarito", "Gaita", "Gaivota",
  "Galho", "Galinha", "Galinheiro", "Galo", "Galpão", "Gamão", "Gâmbia", "Game", "Gamer", "Gana",
  "Gandalf", "Gandhi", "Ganso", "Garagem", "Garapa", "Garçom", "Garfo", "Garganta", "Garoto", "Garoupa",
  "Garra", "Garrafa", "gás", "Gasoso", "Gastão", "Gastrite", "Gato", "Geada", "Gel", "Geladeira",
  "Gelado", "Gelatina", "Geleia", "Gelo", "Gêmeos", "Generoso", "Genética", "Gengibre", "Gengis Khan",
  "Gengiva", "Gengivite", "Genro", "Gentil", "Geógrafo", "Geometria", "Geórgia", "Gerador", "Gérbera", "Gergelim",
  "Gesso", "Gestor", "Giants", "Gif", "Gigabyte", "Gigante", "Gin", "Ginásio", "Girafa", "Girassol",
  "Giz", "Glândula", "Globo", "Glóbulo", "Glúteo", "Goblin", "Gohan", "Goiabada", "Goiânia", "Goiás",
  "Goku", "Gola", "Golden", "Golfe", "Golfinho", "Gollum", "Google", "Google Home", "GoPro", "Gordo",
  "Gospel", "Grafite", "Grammy", "Grampeador", "Grampo", "Granada", "Grande", "Grandes", "Granito", "Granizo",
  "Grão", "Gratidão", "Gravata", "Gravidade", "Grécia", "Grêmio", "Greyhound", "Grifo", "Grimório", "Gripe",
  "Grogue", "Guache", "Guarani", "Guarda", "Guarulhos", "Guatemala", "Gucci", "Gude", "Guerra", "Guerreiro",
  "Gugu", "Guiana", "Guincho", "Guindaste", "Guiné", "Guioza", "Guitarra", "Haas", "Hacker", "Haiti",
  "Hall", "Halloween", "Hambúrguer", "Hamilton", "Hamster", "Handebol", "Hanoi", "Harley-Davidson", "Harmonia", "Harpa",
  "Harry Potter", "Harumaki", "Hashi", "Hashtag", "Hatch", "Havaianas", "Havana", "HD", "HDMI", "Heat",
  "Hela", "Helicóptero", "Hélio", "Helsinque", "Hematoma", "Hera", "Hércules", "Hering", "Hermes", "Hermione",
  "Herói", "Hibisco", "híbrido", "Hidra", "Hidratante", "Hidroavião", "Hidrocor", "Hidrogênio", "Hidromel", "Higiênico",
  "Himalaia", "Hip Hop", "Hipertensão", "Hipopótamo", "Historiador", "Hitchcock", "Hitler", "Holanda", "Homem", "Homem de Ferro",
  "Homem-Aranha", "Homer Simpson", "Homero", "Honda", "Honduras", "Hong Kong", "Hóquei", "Horizonte", "Hormônio", "Horóscopo",
  "Horta", "Hortelã", "Hortênsia", "Horticultura", "hóspedes", "Hospital", "Hossomaki", "Hot", "Hot Wheels", "Hotel",
  "House", "Hoverboard", "HP", "Hulk", "Humilhação", "Hungria", "Husky", "Iate", "Identidade", "Idiossincrasia",
  "Idoso", "Iêmen", "Iene", "Ignorante", "Igreja", "Iguana", "Ilha", "Ilusão", "Ilustração", "Ilustrador",
  "Imagem", "Imobiliário", "Império", "Impermeabilizante", "Imposto", "Impressão", "Impressora", "Incensos", "Inconstitucionalissimamente", "Índia",
  "Indicador", "Indie", "Índigo", "Indonésia", "Indústria", "industrial", "Inexorável", "infantil", "Infecção", "Inferno",
  "Infinito", "Inflação", "Inflamação", "Influencer", "Ingênuo", "inglesa", "Ingresso", "Inimigo", "Inimizade", "Injeção",
  "Injustiça", "Inocência", "Inseticida", "Insosso", "Instagram", "Instável", "Instrumentista", "Instrumento", "Instrutor", "Integral",
  "Inteiro", "Intel", "Inteligência", "Inteligente", "Intenção", "Inter de Milão", "Interesse", "Interface", "Internacional", "Internet",
  "Intérprete", "Interruptor", "Intestino", "íntima", "Intranet", "Introvertido", "Inundação", "Inveja", "Inversora", "Investimento",
  "Iogurte", "Ioiô", "IPA", "Ipê", "iPod", "Ira", "Irã", "Iraque", "íris", "Íris",
  "Irlanda", "Irmã", "Irmandade", "Irmão", "Irritação", "Isaac Newton", "Islamabad", "Islândia", "Isolante", "Israel",
  "Istambul", "Itália", "Itaú", "Iveco", "Ivete Sangalo", "J.K. Rowling", "Jacaré", "Jacarta", "Jade", "Jaguar",
  "Jamaica", "James Bond", "Janela", "jantar", "Japão", "Japonês", "Japonesa", "Jaqueta", "Jardim", "Jardinagem",
  "Jasmim", "Jato", "Javali", "Jazz", "Jeans", "Jeff Bezos", "Jerry", "Jerusalém", "Jesus", "Jinx",
  "Jipe", "jitsu", "Jiu", "Joana d'Arc", "Joanesburgo", "Joaninha", "João Pessoa", "Joe", "Joelheira", "Joelho",
  "Jogador", "Jogo", "jogos", "Jogos", "Jordânia", "Jorge Amado", "Jovem", "Judô", "Juiz", "Julieta",
  "Júlio César", "Junina", "Juros", "Justiça", "Juventus", "K-Pop", "Kani", "Karma", "Katmandu", "Kawasaki",
  "Ken", "Kennedy", "Ketchup", "Kiev", "Kinshasa", "Kitesurf", "Kiwi", "Knicks", "Kraken", "Kratos",
  "Kuala Lumpur", "Kuwait", "Lã", "La Paz", "Lábio", "Labirinto", "Laboratório", "Labrador", "Laço", "Lacta",
  "Ladino", "Lady Gaga", "Lagarto", "Lager", "Lago", "Lagoa", "Lagos", "Lagosta", "Lagostim", "Laje",
  "Lakers", "Lambari", "Lamborghini", "Lamen", "Lâmina", "Lâmpada", "Lançamento", "Lancha", "Land Rover", "Laos",
  "Lápis", "Lapiseira", "Laranja", "Laringe", "Las Vegas", "lata", "Latão", "Latina", "Lava", "Lavabo",
  "Lavanda", "Lavanderia", "Lavoura", "lazúli", "Leal", "leão", "Leão", "Legging", "Lego", "Legolas",
  "leite", "Leite", "Leiteira", "Leitura", "Lêmure", "Lenço", "Lenin", "Lenovo", "Lente", "Lentilha",
  "Lento", "Leonardo da Vinci", "Leopardo", "Lesoto", "Letônia", "Letra", "Leve", "Leviatã", "LG", "Líbano",
  "Liberdade", "Libéria", "Libertadores", "Líbia", "Libra", "Libreville", "Lich", "Licor", "Líder", "Liechtenstein",
  "Ligamento", "Like", "Lilás", "Lima", "Limão", "Limpo", "Limusine", "Lincoln", "Língua", "Linguado",
  "Linguiça", "Linho", "Link", "Liquidificador", "Líquido", "Lira", "Lírio", "Lisa", "Lisboa", "Liso",
  "Lítio", "Lituânia", "Liverpool", "livre", "Livro", "Lixa", "Lixadeira", "Lixeira", "Lobisomem", "Lobo",
  "Lóbulo", "Locomotiva", "Login", "Loja", "Loki", "Lombar", "Lona", "Londres", "Longa", "Lontra",
  "Los Angeles", "Lotus", "Lótus", "Louis Vuitton", "Lousa", "Lua", "Luanda", "Luau", "Lúcifer", "Ludo",
  "Luffy", "Luigi", "Luke Skywalker", "Lula", "Lula Molusco", "Lulu", "Lustra", "Luta", "Luva", "Luvas",
  "Luxação", "Luxemburgo", "Luz", "Lyon", "Maçã", "Macacão", "Macaco", "Macapá", "Macarrão", "Macedônia",
  "Maceió", "Machado", "Machado de Assis", "Maciço", "Macio", "Madagascar", "Madeira", "Madonna", "Madrasta", "Madre Teresa",
  "Madri", "Madrinha", "Mãe", "Maestro", "Magenta", "Magia", "Mágico", "Magnésio", "Mago", "Magro",
  "Maine", "Maiô", "Maionese", "Mal", "Mala", "Malabarista", "Malaquita", "Malásia", "Malaui", "Maldição",
  "Maldivas", "Maldoso", "Malha", "Malho", "Mali", "Malicioso", "Malta", "Maltês", "Mamão", "Mamona",
  "Mana", "Manaus", "Manchester City", "Manchester United", "Mandíbula", "Manga", "Mangue", "Manila", "Manjar", "Manjericão",
  "Manjerona", "Manteiga", "Mão", "Maomé", "Mapa", "Maputo", "Maquiagem", "Máquina", "mar", "Mar",
  "Maradona", "Maratona", "Marca", "Marcenaria", "Marceneiro", "Maremoto", "Margarida", "Margarita", "Marge", "Maria",
  "Marido", "Marilyn Monroe", "Marimba", "marinha", "Marinha", "marinho", "Marinho", "Mario", "Marionete", "Marisco",
  "Mark Zuckerberg", "mármore", "Mármore", "Marreta", "Marrocos", "Marrom", "Marseille", "Martelo", "Martin Luther King", "Martini",
  "Marvel", "Máscara", "Maserati", "Masmorra", "Massa", "Massinha", "Master Chief", "Mastercard", "Mastiff", "Mata",
  "Match", "Mate", "Matemática", "Maternidade", "Maurício", "Mauritânia", "McDonald's", "McLaren", "MDF", "Mecânico",
  "Mecanismo", "Médico", "Médio", "Meditação", "Medo", "Medroso", "Medula", "Medusa", "Meia", "Mel",
  "Melancia", "Melancolia", "Melão", "Melbourne", "Melissa", "Melodia", "Meme", "Memória", "Meninge", "Menisco",
  "Menstrual", "Mentira", "Mentor", "Mercado", "Mercedes", "Mercúrio", "Merendeiro", "Mergulho", "mesa", "Mesa",
  "Mesquita", "Messi", "Meteoro", "metragem", "Metrô", "México", "Mexilhão", "Miami", "Mianmar", "Michael Jackson",
  "Michelangelo", "Mickey", "Micro", "Microfibra", "Microfone", "Microondas", "Microsoft", "Milan", "Milho", "Mimico",
  "Mindinho", "Mineral", "Mini Cooper", "Miniaturas", "Minivan", "Minnie", "Minotauro", "Missoshiro", "Mithril", "Mixer",
  "MMA", "Mocaccino", "Moçambique", "Mochila", "Modelagem", "Moeda", "Moedas", "Mogadíscio", "Mogli", "Moinho",
  "Moisés", "Mojito", "Molar", "Moldávia", "Mole", "Molécula", "Moleque", "Moletom", "Molhado", "Molho",
  "Mônaco", "Monge", "Mongólia", "Monitor", "Monociclo", "Monomotor", "Monopoly", "Monotrilho", "Monstro", "Montanha",
  "Monteiro Lobato", "Montenegro", "Montevidéu", "Monumento", "MOP", "Moral", "Morango", "Morcego", "Moreia", "Morno",
  "Morsa", "Morte", "Morto", "Mosaico", "Moscou", "Mostarda", "Mosteiro", "Motivação", "Moto", "Motocicleta",
  "Motor", "Motorista", "Motorola", "Mountain", "Mouse", "Mousse", "móveis", "Móvel", "Mozart", "MP3",
  "MPB", "Muay", "Muleta", "Mulher Maravilha", "Multiuso", "Mumbai", "Múmia", "Músculo", "Museu", "Musgo",
  "Música", "Musical", "Mussolini", "na", "Nacional", "Nada", "Naftalina", "Naip", "Nairóbi", "Namíbia",
  "namorada", "namorado", "Namorado", "Napoleão", "Napoli", "Narina", "Nariz", "Naruto", "Nascente", "Nascimento",
  "Natação", "Natal", "Natura", "Náutico", "Navegador", "Navio", "Neblina", "Necessaire", "Necromante", "Negociador",
  "Negro", "Negroni", "Nelson Mandela", "Neon", "Nepal", "Nervo", "Nervoso", "Nestlé", "Neta", "Netflix",
  "Neto", "Neurônio", "Nêutron", "Nevasca", "neve", "Neve", "Nevoeiro", "Neymar", "Nicarágua", "Níger",
  "Nigéria", "Niguiri", "Nike", "Nikon", "Nintendo", "Níquel", "Nitrogênio", "Nivea", "Nível", "no",
  "Nocaute", "Noé", "Noite", "Noiva", "Noivado", "Noivo", "Nojo", "Noob", "Nora", "Nori",
  "Noruega", "Nostalgia", "Nota", "Notário", "Notebook", "Nova York", "Nova Zelândia", "Novo", "Noz", "Nozinhos",
  "Nubank", "Nuca", "Nunca", "Nutricionista", "Nuvem", "Nvidia", "Nylon", "Oásis", "Obama", "Obi-Wan",
  "Oboé", "Observação", "Observatório", "Obsidiana", "Oceano", "Oco", "Ocre", "Octógono", "Óculos", "Odin",
  "Ódio", "Oficina", "Oftalmologista", "Ogro", "Óleo", "Olho", "Oliva", "Omã", "Ombro", "Omo",
  "Onça", "ônibus", "Ônibus", "Ônix", "Opaco", "Opala", "Ópera", "operacional", "Operador", "Opressão",
  "Oral-B", "Orangotango", "Orbe", "Orc", "Ordem", "Orégano", "Orelha", "Organizado", "Órgão", "Orgulho",
  "Origami", "Orka Studio", "Orka Zoo", "Orquestra", "Orquídea", "Orvalho", "OSB", "Oscar", "Oslo", "Osso",
  "Ostra", "Otimismo", "Otorrinolaringologista", "Ottawa", "Ouriço", "Ouro", "Ouros", "Ova", "Ovário", "Ovelha",
  "Ovo", "Oxigênio", "Pá", "Pac-Man", "Paciência", "Packers", "Paçoca", "Pacu", "Padeiro", "Padrasto",
  "Padrinho", "Pager", "Pagode", "Pai", "Painel", "País", "Paixão", "Palácio", "Paladino", "Paleta",
  "palhaço", "Palhaço", "Palma", "Palmas", "Palmeiras", "Palmilha", "Pálpebra", "Pamonha", "Panamá", "Panasonic",
  "Pâncreas", "Panda", "Pandeiro", "Panela", "Panetone", "Pânico", "Panificação", "Pano", "Pântano", "Panturrilha",
  "Pão", "Papa Francisco", "Papagaio", "Papai Noel", "papão", "Papel", "papelão", "Papua Nova Guiné", "Paquistão", "Parafusadeira",
  "Parafuso", "Paraguai", "Paralelepípedo", "Parapente", "Paraquedas", "Parceira", "Parceiro", "Parceria", "Pardo", "Parente",
  "Pargo", "Paris", "Parque", "Páscoa", "Pasta", "Pasto", "Pastor", "Paternidade", "Pateta", "Patinete",
  "Patins", "Pato", "Pato Donald", "Patrick", "Patriots", "Pau", "Paulo Coelho", "Paus", "Pauzinhos", "Pavão",
  "Pavê", "Paysandu", "Paz", "Pé", "Peach", "Peça", "Pecado", "Pedagogo", "Pedra", "pedreiro",
  "Pedreiro", "Pedro Álvares Cabral", "Pégaso", "Peito", "Peixe", "Peixeiro", "Peixes", "Pele", "Pelé", "Pelve",
  "Pen", "Peñarol", "Pente", "Pentear", "Pepino", "Pepsi", "Pequeno", "Pequim", "Pera", "Perdão",
  "Perdedor", "Perdigão", "Perfil", "Perfume", "Perfurador", "Perfuratriz", "Pergaminho", "Perito", "Perna", "Pérola",
  "Persa", "Perspicácia", "Peru", "Perua", "Peruca", "Pesadelo", "Pesado", "Pescoço", "Peso", "Pesquisador",
  "Pêssego", "Pessimismo", "Peteca", "petroleiro", "Petúnia", "Philips", "Pia", "Piano", "Pião", "Pica-Pau",
  "Picadeiro", "Picante", "Picape", "Picareta", "Picasso", "Pife", "Pijama", "Pikachu", "Pilar", "Piloto",
  "Pilsen", "Pimenta", "Pimentão", "Piña", "Pinça", "Pincel", "pingue", "Pinguim", "Pinheiro", "Pinscher",
  "Pintado", "Pintor", "Pintura", "Pipa", "Pipoca", "Piquenique", "Piranha", "Pirarucu", "Piscina", "Pista",
  "Pit", "Pitbull", "Pix", "Pixel", "Pizza", "Plaina", "Plainadeira", "Planador", "Planeta", "Planetário",
  "Planície", "Planilha", "Planner", "Planta", "Plantação", "Plaqueta", "Plasma", "Plástico", "Plataforma", "Platina",
  "Playmobil", "PlayStation", "Pluto", "Plutônio", "Pneumonia", "Pó", "Pobre", "Poção", "Pochete", "Poço",
  "Point", "Poke", "Pole", "Polegar", "Policial", "Polido", "Poliéster", "Politriz", "Polo", "Polônia",
  "Polvo", "Pomada", "Pomar", "Pomba", "Pombo", "Pomerânia", "Poncho", "pongue", "Ponte", "Ponte Preta",
  "Poodle", "Pop", "Pôquer", "Porão", "Porcelanato", "Porco", "Poros", "Poroso", "Porsche", "Porta",
  "Portal", "Porteira", "Porto", "Porto Alegre", "Porto Velho", "Portugal", "Pós", "Poseidon", "Position", "Post",
  "Post-it", "Posto", "Potássio", "Pote", "Poupança", "Pousada", "Praça", "Prada", "Praga", "Praia",
  "Prancheta", "Prata", "Prateleira", "Prato", "Prazer", "Prédio", "Prefeitura", "Prego", "Preguiçoso", "Prensa",
  "pressão", "Pressão", "Presunto", "Preta", "Pretendente", "Preto", "Pretória", "Prima", "Primavera", "Primo",
  "Princesa Diana", "Privacidade", "Privada", "Pro", "Proativo", "Processador", "Procrastinação", "Procurador", "Produtor", "Profecia",
  "Professor", "Programa", "Programação", "Programador", "Projetor", "Promotor", "Propósito", "Próstata", "Proteção", "Protetor",
  "Próton", "Província", "PSG", "Psicólogo", "PSV", "Pudim", "Pug", "Pulmão", "Pulôver", "Pulseira",
  "Pulso", "Puma", "Punção", "Punho", "Pupila", "Putin", "PVC", "Quadra", "Quadriciclo", "Quadril",
  "Quadro", "Quartel", "Quarterback", "Quarto", "Quartzo", "que", "Quebra", "Quebrado", "Queijo", "Queixo",
  "Quênia", "Quente", "Querubim", "Quest", "Quimera", "Química", "Quimono", "Quindim", "Quirguistão", "Quito",
  "R&B", "Rã", "Rabanada", "Rachado", "Racional", "Rádio", "Ragdoll", "Raia", "Rainha Elizabeth", "Raio",
  "Raiva", "Raiz", "Ralo", "Rancho", "Rancor", "Ranger", "Rap", "Rapadura", "Rápido", "Raposa",
  "Raquete", "Raspador", "Rato", "Rave", "Real", "Real Madrid", "Reator", "Reboco", "Recepcionista", "Recibo",
  "Recife", "reco", "Reco", "Recorte", "Red Bull", "Red Sox", "Rede", "Rédea", "Redenção", "Reels",
  "Reencarnação", "Refrão", "Refrigerante", "Regata", "Reggae", "Reggaeton", "régia", "Região", "Régua", "Rei",
  "Rei Arthur", "Reino", "Reino Unido", "Rejeição", "Relâmpago", "Relatividade", "Relatório", "Relíquia", "Relógio", "Remo",
  "Remorso", "Removedor", "Renault", "Renda", "Renner", "Renovação", "Repelente", "Representante", "República Checa", "Requeijão",
  "Resfriado", "Resiliência", "Resina", "Resistente", "Resolução", "Respeito", "Responsabilidade", "Ressentimento", "Resta", "Restaurante",
  "Retina", "Retriever", "Retroescavadeira", "reuniões", "Réveillon", "Revestimento", "Riachuelo", "Riad", "Rico", "Rígido",
  "Rihanna", "Rim", "Rinoceronte", "Rio", "Rio Branco", "Rio de Janeiro", "Risada", "Ritmo", "Rivalidade", "River Plate",
  "RNA", "Robalo", "Robata", "Roberto Carlos", "Robô", "Rocha", "Rock", "Rodada", "rodas", "Rodízio",
  "Rodo", "Rodovia", "Rodoviário", "Rolex", "Rolinho", "Roll", "Rolls-Royce", "Rolo", "Roma", "Romance",
  "Romênia", "Romeu", "Rony", "Roosevelt", "Rosa", "Rosário", "Rosé", "Rosto", "Rotatória", "Roteiro",
  "Rottweiler", "Roupa", "Roupão", "Roxo", "Royal", "Royal Enfield", "RPG", "Rua", "Ruanda", "Rubi",
  "Rublo", "Rugby", "Rugoso", "Rum", "Runas", "Rúpia", "Ruptura", "Rússia", "Ryu", "Sabão",
  "Sábio", "Sabonete", "Sacada", "Saco", "Sadia", "Safira", "Sagitário", "Sagu", "Saia", "Saída",
  "Sal", "Sala", "Salada", "Salário", "Salgado", "Salmão", "Salsa", "Salsicha", "Salto", "Salvador",
  "Salvador Dalí", "Sálvia", "Samambaia", "Samba", "Samoa", "Samsung", "San Marino", "Sandália", "Sanduicheira", "Sanfona",
  "Sangue", "Sanitária", "Sanitário", "Santa Cruz", "Santa Lúcia", "Santiago", "Santo", "Santos", "Santuário", "São",
  "São Francisco", "São João", "São Luís", "São Paulo", "São Tomé e Príncipe", "Sapateado", "Sapatilha", "Sapato", "Sapatos", "Sapo",
  "Saquê", "Sardinha", "Sargento", "Sarja", "Sashimi", "Sasuke", "Satanás", "Satélite", "Sátira", "Satisfação",
  "Saudade", "Saudável", "Sauron", "Savanas", "Saxofone", "Scania", "Schumacher", "Scooby-Doo", "Scooter", "Scorpion",
  "Scorsese", "Script", "Seara", "Seca", "Secador", "Seco", "Seda", "Sedã", "Seguidor", "Segurança",
  "Sela", "Selador", "Seleção Alemã", "Seleção Argentina", "Seleção Brasileira", "Seleção Francesa", "Seleção Italiana", "Selos", "Selva", "Semente",
  "Sempiterno", "Sempre", "Senegal", "Senha", "Senna", "Sensor", "Sentido", "Separação", "Septo", "Serafim",
  "Sereia", "Serendipidade", "Serenidade", "Serpente", "serra", "Serra", "Serra Leoa", "Serrote", "Sertanejo", "Sérvia",
  "serviço", "Servidor", "Set", "Seul", "Sevilla", "Shakespeare", "Shakira", "Shampoo", "Sherlock Holmes", "Shih",
  "Shimeji", "Shitake", "Shopping", "Shorts", "Show", "Shoyu", "Siamês", "Siberiano", "Sifão", "Sigilo",
  "Silêncio", "Silício", "Silo", "Silvio Santos", "Simulação", "Sinagoga", "Sinal", "Sinapse", "Sincero", "Singapura",
  "Siri", "Síria", "Siso", "Sistema", "Sitar", "Site", "Sítio", "Skate", "Slide", "Slime",
  "Smartphone", "Smartwatch", "Snowboard", "Sobrado", "Sobrancelha", "Sobretudo", "Sobrinha", "Sobrinho", "Social", "Sócio",
  "Socorrista", "Sódio", "Sofá", "Softbol", "Software", "Sogra", "Sogro", "Soja", "Sol", "Sola",
  "Solar", "Soldador", "Soldadora", "Solidão", "Solidariedade", "Sólido", "Solo", "Som", "Somália", "Sombra",
  "Sombras", "Sommelier", "Sonho", "Sonic", "Sony", "Sorte", "Sorvete", "Sótão", "Soul", "Sovaco",
  "Spam", "Spaniel", "Sphynx", "Spoiler", "Sport", "Sporting", "Spotify", "Sri Lanka", "Stalin", "Stan Lee",
  "Steve Jobs", "Steven Spielberg", "Sticker", "Stop", "Story", "Stout", "Streamer", "Streaming", "Suazilândia", "Sub-Zero",
  "Submarino", "Subúrbio", "Suco", "Suculenta", "Sudão", "Sudare", "Sudoku", "Suécia", "Suéter", "Suíça",
  "Suíte", "Sujo", "Sulfite", "Sunga", "Superman", "Supernova", "Surf", "Suricato", "Suriname", "Surpresa",
  "Sushi", "Suspensa", "Suspense", "Suspiro", "Susto", "Sutiã", "SUV", "Suva", "Suzuki", "Sydney",
  "Tablet", "Tábua", "Tabuleiro", "Taco", "Taekwondo", "Taiga", "Tailândia", "Tails", "Tainha", "Taipei",
  "Taiwan", "Tajiquistão", "Talco", "Talhadeira", "Talher", "Talismã", "Tambaqui", "Tambor", "Tango", "Tanque",
  "Tanzânia", "Tapete", "Tapioca", "Tarantino", "Tarê", "Tarô", "Tartaruga", "Tarzan", "Tatame", "Taverna",
  "Taxista", "Teatro", "Techno", "Teclado", "técnica", "Técnico", "Tecnologia", "Tédio", "Teerã", "Teimoso",
  "Tela", "Teleférico", "Telefone", "Telescópio", "Televisão", "Telha", "Temaki", "Temor", "Tempestade", "Templo",
  "Tempo", "Tempurá", "Tendão", "tênis", "Tênis", "Tensão", "Teppan", "Tequila", "Terapeuta", "Tereré",
  "Teresina", "Teriyaki", "Terminal", "Terno", "Terra", "Terraço", "Terreiro", "Terremoto", "Terror", "Tesla",
  "Tesoura", "Tesoureiro", "Tesouro", "Testa", "Testemunha", "texto", "Texugo", "thai", "Thanos", "Thor",
  "Tia", "Tíbia", "Tie", "Tigre", "Tijolo", "TikTok", "Tilápia", "Timidez", "Tímido", "Timor-Leste",
  "Tímpano", "Tinta", "Tinteiro", "Tio", "Tiradentes", "Tireoide", "Titã", "Titânio", "Toalha", "Toca",
  "Tofu", "Togo", "Tolerância", "Tom", "Tomada", "Tomate", "Tommy Hilfiger", "Tonga", "Topázio", "Tóquio",
  "Torá", "Tórax", "Torção", "Tornado", "Torneira", "Torneiro", "Torno", "Tornozelo", "Torradeira", "Torre",
  "Torresmo", "Torta", "Tosse", "Totalidade", "Tottenham", "Touca", "Touchdown", "Touro", "Toyota", "Tragédia",
  "Traidor", "Trailer", "Trampolim", "Trancado", "Trance", "Transatlântico", "Transferidor", "Transformador", "Translúcido", "Transparente",
  "Trap", "Trapézio", "Trapezista", "Traqueia", "Trator", "Trave", "Travesseiro", "Trem", "Trena", "Trend",
  "Trenó", "Trevas", "Trevo", "Tribunal", "Triciclo", "Tricô", "Trigo", "Trilha", "Trinidad e Tobago", "Tripofobia",
  "Trípoli", "Triste", "Tristeza", "Triumph", "Troll", "Trombone", "Trompa", "Trompete", "Tronco", "Trono",
  "Tropeiro", "Trovão", "Truco", "Trufa", "Trump", "Truque", "Truta", "Tsunami", "Tuba", "Tubarão",
  "Tudo", "Tufão", "Tule", "Tulipa", "Tumba", "Tundra", "Túnel", "Tunísia", "Turbina", "Turcomenistão",
  "Turno", "Turquesa", "Turquia", "Tutela", "Tutor", "Tuvalu", "Twitter", "Tyson", "Tzu", "Uber",
  "Ucrânia", "Udon", "UFC", "Uganda", "Ukulele", "Úlcera", "Ulna", "Um", "Umbigo", "Umedecido",
  "Úmero", "Úmido", "Unha", "União", "Unicórnio", "Uniforme", "Universidade", "Uno", "Upload", "Uramaki",
  "Urânio", "Urbanista", "URL", "Urso", "Uruguai", "Usado", "USB", "Útero", "Utilitário", "Uva",
  "Uzbequistão", "Vaca", "Vacina", "Vagão", "Vaidade", "Vale", "Valencia", "Valete", "Valores", "Valsa",
  "Válvula", "Vampiro", "Van", "Van Gogh", "Vanuatu", "Varanda", "Varinha", "Varsóvia", "Vasco", "Vaso",
  "Vassoura", "Vaticano", "Vazamento", "Vazio", "Veado", "Vedas", "Vegeta", "Veia", "Veja", "Veleiro",
  "Velho", "Veludo", "Vencedor", "Vendedor", "Venezuela", "Ventilador", "Vento", "Ventoinha", "Ventre", "Ventrículo",
  "Verdade", "Verde", "Vergalhão", "Vergonha", "Vermelha", "Vermelho", "Verniz", "Versace", "Verso", "Vesícula",
  "Vestido", "Veterinário", "Viaduto", "Viagem", "Viatura", "Vibração", "Vida", "Vidente", "Videocassete", "Videogame",
  "Vidro", "Vieira", "Viena", "Vietnã", "Viga", "Vila", "Vila Nova", "Vinagre", "Vinho", "Vinil",
  "Viola", "Violão", "Violeta", "Violino", "Violoncelo", "Vira", "Viral", "Virgem", "Virilha", "Virtual",
  "Virtude", "Vírus", "Visa", "Viscose", "Vitória", "viva", "Viveiro", "Vivo", "Vizinho", "Vodka",
  "Voldemort", "Vôlei", "Volkswagen", "Volume", "Volvo", "Vôngole", "Vontade", "Vórtice", "Voz", "VR",
  "Vulcão", "Vulto", "Walkman", "Walt Disney", "War", "Warren Buffett", "Warriors", "Wasabi", "Washington", "Watson",
  "Weiss", "Wellington", "Whisky", "Wi-Fi", "Williams", "Windsurf", "Wok", "Xadrez", "Xangai", "Xarope",
  "Xbox", "Xiaomi", "Xícara", "Xilofone", "Xuxa", "Yakisoba", "Yamaha", "Yankees", "Yoda", "Yoga",
  "Yorkshire", "YouTube", "Youtuber", "Yuan", "Zâmbia", "Zara", "Zebra", "Zelda", "Zeus", "Zimbábue",
  "Zinco", "Zíper", "Zoológico", "Zumba", "Zumbi",
  "Alfaiate", "Alquimista", "Altruísmo", "Aluvião", "Ampulheta", "Anticiclone", "Anzol", "Aparador", "Apicultor", "Arandela", 
  "Arqueólogo", "Arrogância", "Atol", "Baía", "Barreira", "Basalto", "Benevolência", "Bibliotecário", "Biólogo", "Bisturi", 
  "Bocal", "Bodega", "Bravura", "Bússola", "Cânion", "Canteiro", "Cascata", "Castiçal", "Catraca", "Censor", 
  "Chocalho", "Claquete", "Clérigo", "Cobiça", "Comissário", "Coreógrafo", "Cume", "Dádiva", "Dedal", "Degelo", 
  "Degustador", "Desentupidor", "Desprezo", "Diapasão", "Dilema", "Diplomata", "Dobradiça", "Dramaturgo", "Duna", "Ecólogo", 
  "Eloquência", "Empenho", "Enigma", "Enseada", "Escarpa", "Escritor", "Esmeril", "Estatístico", "Estepe", "Estojo", 
  "Estribo", "Falésia", "Fascínio", "Fenda", "Ferreiro", "Fervor", "Figurinista", "Fisga", "Fole", "Forense", 
  "Foz", "Frenesi", "Funil", "Fuso", "Ganância", "Garimpeiro", "Gêiser", "Geleira", "Geólogo", "Gotejador", 
  "Gramofone", "Grotão", "Gula", "Hélice", "Hesitação", "Holofote", "Honra", "Horticultor", "Igapó", "Igarapé", 
  "Ilusionista", "Ímpeto", "Imunologista", "Incensário", "Inércia", "Iogurteira", "Ironia", "Isqueiro", "Jaleco", "Jarra", 
  "Jazida", "Jornaleiro", "Jornalista", "Júbilo", "Junco", "Junta", "Lacre", "Lama", "Lampião", "Lascívia", 
  "Leiloeiro", "Limo", "Lume", "Luneta", "Luthier", "Maçarico", "Manguezal", "Manivela", "Maresia", "Melancolia", 
  "Mensageiro", "Mergulhador", "Mina", "Modéstia", "Modista", "Mordaça", "Narguilé", "Navalha", "Névoa", "Novelo", 
  "Ojeriza", "Oratório", "Ourives", "Ouvidoria", "Pélago", "Pêndulo", "Península", "Piedade", "Planalto", "Poeta", 
  "Prumo", "Pua", "Pudor", "Querosene", "Quilha", "Quilombola", "Químico", "Rancidez", "Rebolo", "Relojoeiro", 
  "Renúncia", "Ribeirão", "Roldana", "Roteador", "Roteirista", "Sarcasmo", "Seringa", "Serralheiro", "Sertão", "Silicato", 
  "Sino", "Soberba", "Soldado", "Sondador", "Sossego", "Suporte", "Tecelão", "Topógrafo", "Torpor", "Tradutor", 
  "Trinco", "Triturador", "Tubo", "Turfa", "Ufania", "Utopia", "Velejador", "Vigor", "Vingança", "Volante", "Zelo",
  "Ninho", "Cigarro", "Charuto", "Cadeado"
];

export const palavrasEN = [
  "3D", "Pineapple", "Abdomen", "Bee", "Open", "Abyss", "Pumpkin", "Zucchini", "Absinthe", "Sanitary Pad",
  "Abuja", "Gym", "Acai", "Action", "Chance", "Ace", "Acceptance", "Acer", "Acetone", "Steel",
  "Chord", "Accordion", "Butcher", "Acrylic", "Acrophobia", "Sugar", "Weir", "Dagger", "Adamantium", "Wine Cellar",
  "Ades", "Sticker", "Adidas", "Addis Ababa", "Administrator", "Admiration", "Adoption", "Lawyer", "Airport", "Afghanistan",
  "Affection", "Goddaughter", "Godson", "South Africa", "Aphrodite", "Agate", "Planner", "Agogo", "Agorafobia", "Sweet and Sour",
  "Water", "Eagle", "Airfryer", "Ajax", "Akita", "Albania", "Hostel", "Albert Einstein", "Album", "Moose",
  "Quran", "Village", "Rosemary", "Joy", "Germany", "German", "Allergy", "Alexa", "Alexander the Great", "Alfa Romeo",
  "Lettuce", "Algae", "Algebra", "Cotton", "Algorithm", "Garlic", "Ali", "Ally", "Alliance", "Pliers",
  "Relief", "Soul", "Cushion", "Warehouse", "Mountaineering", "Alchemy", "Altar", "High", "Altruistic", "Height",
  "Aluminum", "Target", "Amman", "Fabric Softener", "Lover", "Hopscotch", "Yellow", "Bitter", "Dented", "Amazon",
  "Amber", "Ambulance", "AMD", "Almond", "Peanut", "Amethyst", "Tonsil", "Friendship", "Love", "Amsterdam",
  "Amulet", "Analyst", "Dwarf", "Ankara", "Anchovy", "Rake", "Swallow", "Andorra", "Ring", "Ring Finger",
  "Anemone", "Host", "Angola", "Angora", "Indigo", "Animation", "Animator", "Anitta", "Birthday", "Angel",
  "New Year", "Anxiety", "Anxious", "Forearm", "Antenna", "Anteroom", "Ancient", "Antelope", "Aorta", "Eraser",
  "Device", "Apartment", "Apathy", "Attachment", "Appendix", "Applause", "App", "Apocalypse", "Apollo", "Sharpener",
  "Retirement", "Apple", "Apprentice", "Fold", "Aquaman", "Watercolor", "Aquarium", "Aquatic", "Heater", "Achilles",
  "Saudi Arabia", "Aracaju", "Arachnophobia", "Plow", "Aragorn", "Wire", "Spider", "Archangel", "Arch", "Slate",
  "Area", "Sand", "Arena", "Herring", "Ares", "Mortar", "Algiers", "Algeria", "Argentina", "Clay",
  "Ring", "Argon", "Aries", "Armor", "Armani", "Closet", "Warehouse", "Armenia", "Air Freshener", "Bleachers",
  "Archipelago", "Architect", "File", "Stingray", "Throw", "Regret", "Rice", "Rue", "Arsenal", "Artifact",
  "Artemis", "Artery", "Handicraft", "Joint", "Artificial", "Tree", "Ace", "Wing", "Ascendant", "Asphalt",
  "Ash", "Asthma", "Rough", "Vacuum Cleaner", "Seat", "Assistant", "Ghost", "Asuncion", "Asteroid", "Aston Martin",
  "Astral", "Astronomy", "Asus", "Atabaque", "Studio", "Athena", "Athens", "Attendant", "Athletico Paranaense", "Shooter",
  "Atletico Madrid", "Atletico Mineiro", "Athletics", "Atom", "Actor", "Actress", "Update", "Tuna", "Auckland", "Audi",
  "Auditor", "Audrey Hepburn", "Aura", "Aurora", "Australia", "Austria", "Automation", "Automobile", "Slot Car", "Avai",
  "Avalanche", "Evaluator", "Miser", "Oats", "Avenue", "Apron", "Adventure", "Airplane", "Airplanes", "Grandmother",
  "Grandfather", "Avon", "Axe", "Armpit", "Azalea", "Bad Luck", "Sour", "Olive Oil", "Azerbaijan", "Blue",
  "Tile", "Aloe Vera", "Curling Iron", "Cod", "Bach", "Basin", "Backup", "Spleen", "Bacon", "Bacteria",
  "Grouper", "Badminton", "Baghdad", "Messy", "Bahamas", "Bahia", "Bahrain", "Pufferfish", "Neighborhood", "Low",
  "Party", "Balloon", "Shop Assistant", "Bucket", "Whale", "Ballet", "Ferry", "Expert", "Hula Hoop", "Bamboo",
  "Banana", "Banker", "Bank", "Bank of Brazil", "Band", "Mandolin", "Bangkok", "Bangladesh", "Bathtub", "Bathroom",
  "Banjo", "Bar", "Beard", "Barbados", "Barbarian", "Razor", "Shave", "Barbie", "Large Boat", "Barcelona",
  "Boat", "Bard", "Barney", "Bar", "Dam", "Belly", "Bart", "Bartender", "Basketball", "Basketball",
  "Basset", "Stick", "Potato", "Mixer", "Battery", "Shake", "Baptism", "Batman", "Bayern Munich", "Beagle",
  "Baby", "Beethoven", "Beige", "Begonia", "Coconut Truffle", "Beirut", "Baseball", "Belem", "Belgium", "Belize",
  "Belo Horizonte", "Beelzebub", "Good", "Benfica", "Bengal", "Benin", "Bentley", "Beryllium", "Berimbau", "Eggplant",
  "Berlin", "Shorts", "Bern", "Bernard", "Cattle Horn", "Beetle", "Concrete Mixer", "Bladder", "Beyonce", "Bible",
  "Library", "Beast", "Bicycle", "Beak", "Biden", "Belarus", "Big Bang", "Bike", "Marble", "Ticket Office",
  "Bile", "Bill Gates", "Twin-engine", "Biology", "Biome", "Pager", "Biplane", "Bikini", "Bison", "Great-grandmother",
  "Great-grandfather", "Cookie", "Great-granddaughter", "Great-grandson", "Bitcoin", "Blazer", "Block", "Blog",
  "Blu-ray", "Blues", "Bluetooth", "Blouse", "BMW", "Boa Vista", "SpongeBob", "Mouth", "Boca Juniors", "Bocce",
  "Cheek", "Bogota", "Ball", "Bolero", "Bank Slip", "Bowling", "Bolivia", "Cake", "Bag", "Pocket",
  "Bolsonaro", "Bomb", "Mumbai", "Firefighter", "Chocolate Candy", "Steel Wool", "Tram", "Kind", "Cap", "Doll",
  "Action Figure", "Beautiful", "Bonsai", "Butterfly", "Embroidery", "Border", "Bordeaux", "Boreal", "Boron", "Eraser",
  "Rubber", "Borussia Dortmund", "Bosnia", "Grove", "Bossa Nova", "Boot", "Botafogo", "Button", "Apothecary", "Botswana",
  "Bowser", "Box", "Boxing", "Boxer", "Arm", "Bradesco", "White", "White", "Brazil", "Brazilian League",
  "Brasilia", "Brazzaville", "Break", "Marsh", "Chocolate Truffle", "Earring", "Breeze", "Gravel", "Jackhammer", "Broccoli",
  "Bromeliad", "Bronchitis", "Bronze", "Brunei", "Brussels", "Sponge", "Buddha", "Budapest", "Buenos Aires", "Buffalo",
  "Bugatti", "Bulgaria", "Bulldog", "Bulls", "Hole", "Burger King", "Burkina Faso", "Donkey", "Donkey", "Burundi",
  "Bhutan", "Horn", "C&A", "Head", "Head", "Hair", "Cable", "Cape Verde", "Halter", "Kabul", "Casserole", "Cachaca",
  "Scarf", "Cacheta", "Waterfall", "Dog", "Cactus", "Shoelace", "Chair", "Shooting Star", "Notebook", "Coffee",
  "Coffee Maker", "Kayak", "Hillbilly", "Caipirinha", "Cairo", "Box", "Staff", "Cashew Truffle", "Lime", "Pants",
  "Pants", "Heel", "Panties", "Calcium", "Calculator", "Calculus", "Boiler", "Broth", "Kaleidoscope", "Calendar",
  "Calligraphy", "Calm", "Quiet", "Calvin Klein", "Bed", "Chamber", "Shrimp", "Dressing Room", "Cameroon", "Canberra",
  "Cambodia", "Camel", "Camera", "Walk", "Truck", "Trucker", "Pickup Truck", "Shirt", "T-shirt", "Chamomile",
  "Campinas", "Camping", "Field", "Field", "Campo Grande", "Suede", "Cane", "Canada", "Song", "Cancer",
  "Cinnamon", "Shin Guard", "Pen", "Marker", "Felt-tip Pen", "Kangaroo", "Cannon", "Canine", "Pocket Knife", "Canjica",
  "Canoe", "Canon", "Canson", "Corner", "Singer", "Singer", "Chaos", "Helmet", "Chapel", "Capital",
  "Captain", "Captain America", "Cappuccino", "Capricorn", "Hood", "Persimmon", "Face", "Face", "Caracas", "Snail",
  "Caramel", "Crab", "Karate", "Carbon", "Cargo Ship", "Cavity", "Stamp", "Affection", "Carlos Drummond", "Crimson",
  "Carnival", "Meat", "Carolina", "Carpaccio", "Carpenter", "Charger", "Stroller", "Car", "Cart", "Letter",
  "Card", "Cards", "Wallet", "Mailman", "Cartilage", "Top Hat", "Poster Board", "Registry", "Cartoon", "Coal",
  "House", "Casablanca", "Coat", "Couple", "Wedding", "Peel", "Cassette", "Chestnut", "Castle", "Qatar",
  "Pinwheel", "Cathedral", "Mackerel", "Easel", "Horse", "Cavaquinho", "Caviar", "Kazakhstan", "CD", "Ceara",
  "Onion", "Chive", "Barn", "Celtics", "Cell", "Cell Phone", "Cemetery", "Scene", "Carrot", "Centaur",
  "Central", "Center", "Wax", "Ceramic", "Fence", "Cereal", "Brain", "Beer", "Basket", "Basket",
  "Skepticism", "Satin", "Sky", "Ceviche", "Tea", "Small Farm", "Chad", "Chakra", "Kettle", "Flame",
  "Champagne", "Champions League", "Chanel", "Chapecoense", "Hat", "Flat Iron", "Charlie Chaplin", "Gig", "Chatbot", "Key",
  "Che Guevara", "Cheese", "Chef", "Boss", "Full", "Chelsea", "Check", "Chevrolet", "Chicago", "Whip",
  "Chihuahua", "Chile", "Chimarrao", "Chimpanzee", "China", "Sandal", "Cyprus", "Pigsty", "Chocolate", "Chocotone",
  "Draft Beer", "Shock", "Chow", "Lead", "Chun-Li", "Churchill", "Barbecue", "Churros", "Rain", "Rain",
  "Shower", "Cyan", "Scar", "Cycling", "Cyclone", "Cyclops", "City", "Citadel", "Citron", "Scientific",
  "Scientist", "Eyelashes", "Cement", "Cinema", "Singapore", "Belt", "Waist", "Belt", "Gray", "Circus",
  "Circuit", "Circular", "Swan", "Citrine", "Jealousy", "Clarity", "Clarice Lispector", "Clarinet", "Clear", "Clear",
  "Classical", "Claustrofobia", "Clavicle", "Cleopatra", "Cleric", "Client", "Clinic", "Clips", "Chlorine", "Closet",
  "CNC", "Curd", "Blanket", "Snake", "Copper", "Coca-Cola", "Coconut Candy", "Coccyx", "Stable", "Cocker",
  "Coconut", "Coding", "Code", "Quail", "Easter Bunny", "Rabbit", "Coriander", "Safe", "Mushroom", "Glue",
  "Colada", "Collage", "Collapse", "Necklace", "Collecting", "Colleague", "School", "Cholesterol", "Vest", "Collector",
  "Colgate", "Harvester", "Spoon", "Hill", "Collie", "Colombia", "Colony", "Column", "With", "Godmother",
  "Commander", "Beginning", "Comedy", "Comment", "Merchant", "Comet", "Comoros", "Godfather", "Compassion", "Companion",
  "Companion", "Sharing", "Compass", "Plywood", "Competition", "Composition", "Composer", "Buyer", "Understanding", "Compressor",
  "Pill", "Computer", "Concert", "Concrete", "Condemnation", "Condensed", "Conditioner", "Conductor", "Connection", "Bakery",
  "Pastry Chef", "Trust", "Conflict", "Comfort", "Confusion", "Congo", "Brandy", "Acquaintance", "Conscience", "Consequence",
  "Console", "Consultant", "Accountant", "Continent", "Contortionist", "Double Bass", "Contract", "Controller", "Control", "Convertible",
  "Guest", "Coexistence", "Coon", "Cooperation", "Cup", "World Cup", "Hearts", "Copenhagen", "Glass", "Cocktail",
  "Color", "Heart", "Courage", "Brave", "Coral", "Rope", "String", "North Korea", "South Korea", "Joker",
  "Corinthians", "Coritiba", "Cornea", "Bugle", "Crown", "Hallway", "Stream", "Mail", "Correction Fluid", "Broker",
  "Race", "Race", "Cutter", "Cut", "Court", "Curtain", "Owl", "Crow", "Cosmopolitan", "Coast",
  "Ivory Coast", "Costa Rica", "Back", "Rib", "Sewing", "Cotton Swab", "Elbow Pad", "Elbow", "Combat Boot", "Country",
  "Leather", "Kale", "Cowardice", "Cowboys", "Thigh", "Kitchen", "Cook", "Badge", "Crater", "Clove",
  "Cream", "Credit", "Cream", "Crepe", "Crepe Paper", "Creation", "Creative", "Cryptography", "Cryptocurrency", "Cricket",
  "Crystals", "Crystal", "Cristiano Ronaldo", "Croatia", "Crochet", "Crocodile", "Crossover", "Cruel", "Crush", "Crossing",
  "Cruzeiro", "Cuba", "Cube", "Briefs", "Cuiaba", "Care", "Cooking", "Guilt", "Cultivation", "Accomplice",
  "Sister-in-law", "Brother-in-law", "Cupuacu", "Bandage", "Corn Pudding", "Curiosity", "Curitiba", "Corral", "Short", "of",
  "Dhaka", "Dakar", "Dachshund", "Die", "Data", "Dalai Lama", "Dalmatian", "Lady", "Checkers", "Apricot",
  "Dance", "Damaged", "Dante Alighieri", "Darth Vader", "Type", "DC", "of", "From", "Debit", "Disappointment",
  "Neckline", "Big Toe", "Finger", "Defender", "Police Station", "Chief of Police", "Delhi", "Dell", "Delta", "Delta",
  "Demon", "Dense", "Dental", "Tooth", "Teeth", "Dentist", "Warehouse", "Depressed", "Dermis", "Discouragement",
  "Flush", "Distrust", "Discomfort", "Desire", "Drawing", "Developer", "Desert", "Despair", "Designer", "Disinfectant",
  "Landslide", "Deodorant", "Dispatch", "Pantry", "Destiny", "Unlocked", "Destruction", "Detergent", "Determination", "Detective",
  "Dethrone", "Duty", "Dharma", "Day", "Mother's Day", "Valentine's Day", "Father's Day", "Diabetes", "Diaphragm", "Diamond",
  "Dimension", "Denmark", "Money", "Dior", "Diova", "Dike", "Law", "Director", "Airship", "Discman",
  "Discs", "Disney", "Device", "Floppy Disk", "Distancing", "Distributor", "District", "Debt", "Divorce", "Djibouti",
  "DNA", "of", "Doberman", "Folded", "Origami", "Sweet", "Documentary", "Document", "Dodgers", "Sick",
  "Dojo", "Dollar", "Dom Pedro", "Tamer", "Dominica", "Dominoes", "Weasel", "Pain", "Dormitory", "Back",
  "Golden", "Dove", "Download", "Dracula", "Dragon", "Drama", "Drive", "Drone", "Druid", "Dubai",
  "Stuntman", "Dublin", "Ducati", "Dumbledore", "Dungeon", "Dunk", "Pair", "Tape", "Hard", "Hard",
  "Doubt", "DVD", "Eclair", "Eclipse", "Echo", "Economist", "Ecosystem", "Edition", "Building", "Educator",
  "Ephemeral", "Egypt", "Ego", "Selfish", "El Salvador", "Spandex", "Elastic", "Elastic Band", "Elephant", "Electrical",
  "Electrician", "Electric", "Electron", "Electronics", "Elevator", "Elf", "Elixir", "Elon Musk", "Elvis Presley", "In",
  "Email", "United Arab Emirates", "Emmy", "Emoji", "Tie", "Empathy", "Forklift", "Employee", "Company", "Loan",
  "Plumber", "Enchantment", "Soaked", "Flood", "Energy", "Nurse", "Rusty", "Engineer", "Swallower", "Eel",
  "Stepdaughter", "Stepson", "Entrance", "Delivery Man", "Enthusiasm", "Envelope", "Hoe", "Mouthwash", "Migraine", "Sulfur",
  "Epidermis", "Ecuador", "Balance", "Tightrope Walker", "Equipment", "Eritrea", "Eruption", "Pea", "Staircase", "Scale",
  "Climbing", "Scale", "Scapula", "Scarlet", "Excavator", "School", "Choice", "Scorpion", "Drainer", "Brush",
  "Writing", "Office", "Clerk", "Shield", "Sculpture", "Schooner", "Dark", "Dark", "Fencing", "Slovakia",
  "Slovenia", "Nail Polish", "Emerald", "Esophagus", "Space", "Spaceship", "Sword", "Sword", "Spades", "Duster",
  "Spain", "Scarecrow", "Spatula", "Spectrum", "Mirror", "Hope", "Smart", "Spectacle", "Spinach", "Spiritism",
  "Spirit", "Sneeze", "Sponge", "Sporty", "Wife", "Juicer", "Foam", "Sparkling Wine", "Square Ruler", "Skeleton",
  "Skiing", "Squirrel", "Essence", "Stable", "Station", "Parking Lot", "Stadium", "State", "United States", "Statewide",
  "Tin", "Shelf", "Being", "Statistics", "Stable", "Conveyor Belt", "Sternum", "Drought", "Box Cutter", "Slingshot",
  "Stockholm", "Stomach", "Estonia", "Road", "Strange", "Premiere", "Star", "Stressed", "Estuary", "Studio",
  "Ether", "Eternity", "Ethereum", "Ethics", "Ethiopia", "Label", "Eucalyptus", "Euphoria", "Euphoric", "Euro",
  "Evolution", "Ex", "Exhaustion", "Eccentricity", "Existence", "Exhibition", "Espresso", "External", "Extractor", "Extroverted",
  "Factory", "Knife", "Machete", "Knives", "Face", "Facebook", "Fairy", "Tooth Fairy", "Banner", "Speaker",
  "Falcon", "False", "Family", "Fantasy", "Ghost", "Puppet", "Uniform", "Flour", "Pharmacist", "Pharmacy",
  "Western", "Barbed", "Fascination", "Faustao", "Fax", "Farm", "Faith", "Fever", "Closed", "Lock",
  "Beans", "Ugly", "Market", "Sorcerer", "Spell", "Happy", "Femur", "Crack", "Phoenix", "Holiday",
  "Vacation", "Wound", "Fernando Pessoa", "Horseshoe", "Tool", "Ferrari", "Iron", "Toy Train", "Rust", "Party",
  "Festival", "Fiat", "Fiber", "Fibula", "Fiction", "Form", "Binder", "Fidel Castro", "Liver", "Figueirense",
  "Fiji", "Daughter", "Son", "Affiliation", "Philippines", "Filming", "Philosopher", "Filter", "End", "Finish",
  "Financial", "Financing", "Finland", "Wire", "Firewall", "Fiscal", "Physics", "Physiotherapist", "Tape", "Tape",
  "Buckle", "Fixed", "Flamenco", "Flamengo", "Flannel", "Flash", "Flute", "Piccolo", "Arrow", "Flexible",
  "Flower", "Forest", "Florianopolis", "Fluminense", "Fluorine", "Phobia", "Seal", "Stove", "Bonfire", "Rocket",
  "Scythe", "Leaf", "Follicle", "Folk", "Headphone", "Ford", "Chisel", "Graduation", "Ant", "Supplier",
  "Oven", "Forro", "Fortaleza", "Strong", "Match", "Photography", "Weak", "Fragile", "Diaper", "France",
  "Franc", "Chicken", "Frankenstein", "Fracture", "Fred", "Freezer", "Milling Machine", "Fresh", "Freya", "Frying Pan",
  "Cold", "Frodo", "Border", "Frustration", "Fruits", "Fuchsia", "Fungus", "Funicular", "Funk", "Hurricane",
  "Drill", "Soccer", "Soccer", "Futsal", "Gabon", "Answer Key", "Harmonica", "Seagull", "Branch", "Chicken",
  "Chicken Coop", "Rooster", "Shed", "Backgammon", "Gambia", "Game", "Gamer", "Ghana", "Gandalf", "Gandhi",
  "Goose", "Garage", "Sugar Cane Juice", "Waiter", "Fork", "Throat", "Boy", "Grouper", "Claw", "Bottle",
  "Gas", "Gaseous", "Gastao", "Gastritis", "Cat", "Frost", "Gel", "Refrigerator", "Cold", "Gelatin",
  "Jam", "Ice", "Twins", "Generous", "Genetics", "Ginger", "Genghis Khan", "Gum", "Gingivitis", "Son-in-law",
  "Gentle", "Geographer", "Geometry", "Georgia", "Generator", "Gerbera", "Sesame", "Plaster", "Manager", "Giants",
  "Gif", "Gigabyte", "Giant", "Gin", "Gymnasium", "Giraffe", "Sunflower", "Chalk", "Gland", "Globe",
  "Globule", "Glute", "Goblin", "Gohan", "Guava Paste", "Goiania", "Goias", "Goku", "Collar", "Golden",
  "Golf", "Dolphin", "Gollum", "Google", "Google Home", "GoPro", "Fat", "Gospel", "Graphite", "Grammy",
  "Stapler", "Staple", "Grenade", "Big", "Great", "Granite", "Hail", "Grain", "Gratitude", "Tie",
  "Gravity", "Greece", "Gremio", "Greyhound", "Griffin", "Grimoire", "Flu", "Groggy", "Gouache", "Guarani",
  "Guard", "Guarulhos", "Guatemala", "Gucci", "Marble", "War", "Warrior", "Gugu", "Guyana", "Tow Truck",
  "Crane", "Guinea", "Gyoza", "Guitarra", "Haas", "Hacker", "Haiti", "Hall", "Halloween", "Hamburger",
  "Hamilton", "Hamster", "Handball", "Hanoi", "Harley-Davidson", "Harmony", "Harp", "Harry Potter", "Spring Roll", "Chopsticks",
  "Hashtag", "Hatchback", "Havaianas", "Havana", "HD", "HDMI", "Heat", "Hela", "Helicopter", "Helium",
  "Helsinki", "Bruise", "Ivy", "Hercules", "Hering", "Hermes", "Hermione", "Hero", "Hibiscus", "Hybrid",
  "Hydra", "Moisturizer", "Seaplane", "Marker", "Hydrogen", "Mead", "Hygienic", "Himalayas", "Hip Hop", "Hypertension",
  "Hippopotamus", "Historian", "Hitchcock", "Hitler", "Netherlands", "Man", "Iron Man", "Spider-Man", "Homer Simpson", "Homer",
  "Honda", "Honduras", "Hong Kong", "Hockey", "Horizonte", "Hormone", "Horoscope", "Vegetable Garden", "Mint", "Hydrangea",
  "Horticulture", "Guests", "Hospital", "Hossomaki", "Hot", "Hot Wheels", "Hotel", "House", "Hoverboard", "HP",
  "Hulk", "Humiliation", "Hungary", "Husky", "Yacht", "Identity", "Idiosyncrasy", "Elderly", "Yemen", "Yen",
  "Ignorant", "Church", "Iguana", "Island", "Illusion", "Illustration", "Illustrator", "Image", "Real Estate", "Empire",
  "Waterproofing", "Tax", "Print", "Printer", "Incense", "Unconstitutionally", "India", "Indicator", "Indie", "Indigo",
  "Indonesia", "Industry", "Industrial", "Inexorable", "Infantile", "Infection", "Hell", "Infinite", "Inflation", "Inflammation",
  "Influencer", "Naive", "English", "Ticket", "Enemy", "Enmity", "Injection", "Injustice", "Innocence", "Insecticide",
  "Bland", "Instagram", "Unstable", "Instrumentalist", "Instrument", "Instructor", "Integral", "Whole", "Intel", "Intelligence",
  "Intelligent", "Intention", "Inter Milan", "Interest", "Interface", "International", "Internet", "Interpreter", "Switch", "Intestine",
  "Intimate", "Intranet", "Introverted", "Flood", "Envy", "Inverter", "Investment", "Yogurt", "Yo-yo", "IPA",
  "Ipe Tree", "iPod", "Wrath", "Iran", "Iraq", "Iris", "Iris", "Ireland", "Sister", "Brotherhood",
  "Brother", "Irritation", "Isaac Newton", "Islamabad", "Iceland", "Insulator", "Israel", "Istanbul", "Italy", "Itau",
  "Iveco", "Ivete Sangalo", "J.K. Rowling", "Alligator", "Jakarta", "Jade", "Jaguar", "Jamaica", "James Bond", "Window",
  "Dinner", "Japan", "Japanese", "Japanese", "Jacket", "Garden", "Gardening", "Jasmine", "Jet", "Wild Boar",
  "Jazz", "Jeans", "Jeff Bezos", "Jerry", "Jerusalem", "Jesus", "Jinx", "Jeep", "Jitsu", "Jiu",
  "Joan of Arc", "Johannesburg", "Ladybug", "Joao Pessoa", "Joe", "Knee Pad", "Knee", "Player", "Game", "Games",
  "Games", "Jordan", "Jorge Amado", "Young", "Judo", "Judge", "Juliet", "Julius Caesar", "Junina", "Interest",
  "Justice", "Juventus", "K-Pop", "Kani", "Karma", "Kathmandu", "Kawasaki", "Ken", "Kennedy", "Ketchup",
  "Kyiv", "Kinshasa", "Kitesurfing", "Kiwi", "Knicks", "Kraken", "Kratos", "Kuala Lumpur", "Kuwait", "Wool",
  "La Paz", "Lip", "Labyrinth", "Laboratory", "Labrador", "Bow", "Lacta", "Ladino", "Lady Gaga", "Lizard",
  "Lager", "Lake", "Lagoon", "Lagos", "Lobster", "Crayfish", "Slab", "Lakers", "Lambari Fish", "Lamborghini",
  "Ramen", "Blade", "Light Bulb", "Release", "Motorboat", "Land Rover", "Laos", "Pencil", "Mechanical Pencil", "Orange",
  "Larynx", "Las Vegas", "Can", "Brass", "Latina", "Lava", "Powder Room", "Lavender", "Laundry Room", "Crop",
  "Lazuli", "Loyal", "Lion", "Lion", "Leggings", "Lego", "Legolas", "Milk", "Milk", "Milk Jug",
  "Reading", "Lemur", "Handkerchief", "Lenin", "Lenovo", "Lens", "Lentil", "Slow", "Leonardo da Vinci", "Leopard",
  "Lesotho", "Latvia", "Letter", "Light", "Leviathan", "LG", "Lebanon", "Freedom", "Liberia", "Libertadores",
  "Libya", "Libra", "Libreville", "Lich", "Liqueur", "Leader", "Liechtenstein", "Ligament", "Like", "Lilac",
  "Lima", "Lemon", "Clean", "Limousine", "Lincoln", "Language", "Flounder", "Sausage", "Linen", "Link",
  "Blender", "Liquid", "Lyre", "Lily", "Smooth", "Lisbon", "Straight", "Lithium", "Lithuania", "Liverpool",
  "Free", "Book", "Sandpaper", "Sander", "Trash Can", "Werewolf", "Wolf", "Lobe", "Locomotive", "Login",
  "Shop", "Loki", "Lumbar", "Tarp", "London", "Feature Film", "Otter", "Los Angeles", "Lotus", "Lotus",
  "Louis Vuitton", "Blackboard", "Moon", "Luanda", "Luau", "Lucifer", "Ludo", "Luffy", "Luigi", "Luke Skywalker",
  "Squid", "Squidward", "Pomeranian", "Polish", "Fight", "Glove", "Gloves", "Dislocation", "Luxembourg", "Light",
  "Lyon", "Apple", "Overalls", "Monkey", "Macapa", "Pasta", "Macedonia", "Maceio", "Axe", "Machado de Assis",
  "Massif", "Soft", "Madagascar", "Wood", "Madonna", "Stepmother", "Mother Teresa", "Madrid", "Godmother", "Mother",
  "Conductor", "Magenta", "Magic", "Magician", "Magnesium", "Wizard", "Thin", "Maine", "Swimsuit", "Mayonnaise",
  "Evil", "Suitcase", "Juggler", "Malachite", "Malaysia", "Malawi", "Curse", "Maldives", "Wicked", "Mesh",
  "Mallet", "Mali", "Malicious", "Malta", "Maltese", "Papaya", "Castor Bean", "Sister", "Manaus", "Manchester City",
  "Manchester United", "Jaw", "Mango", "Mangrove", "Manila", "Delicacy", "Basil", "Marjoram", "Butter", "Hand",
  "Muhammad", "Map", "Maputo", "Makeup", "Machine", "Sea", "Sea", "Maradona", "Marathon", "Brand",
  "Carpentry", "Carpenter", "Seaquake", "Daisy", "Margarita", "Marge", "Maria", "Husband", "Marilyn Monroe", "Marimba",
  "Navy", "Navy", "Marine", "Navy Blue", "Mario", "Puppet", "Shellfish", "Mark Zuckerberg", "Marble", "Marble",
  "Sledgehammer", "Morocco", "Brown", "Marseille", "Hammer", "Martin Luther King", "Martini", "Marvel", "Mask", "Maserati",
  "Dungeon", "Pasta", "Playdough", "Master Chief", "Mastercard", "Mastiff", "Forest", "Match", "Mate", "Mathematics",
  "Maternity", "Mauritius", "Mauritania", "McDonald's", "McLaren", "MDF", "Mechanic", "Mechanism", "Doctor", "Medium",
  "Meditation", "Fear", "Fearful", "Marrow", "Medusa", "Sock", "Honey", "Watermelon", "Melancholy", "Melon",
  "Melbourne", "Melissa", "Melody", "Meme", "Memory", "Meninges", "Meniscus", "Menstrual", "Lie", "Mentor",
  "Market", "Mercedes", "Mercury", "School Cook", "Diving", "Table", "Table", "Mosque", "Messi", "Meteor",
  "Footage", "Subway", "Mexico", "Mussel", "Miami", "Myanmar", "Michael Jackson", "Michelangelo", "Mickey", "Micro",
  "Microfiber", "Microphone", "Microwave", "Microsoft", "Milan", "Corn", "Mime", "Pinky Finger", "Mineral", "Mini Cooper",
  "Miniatures", "Minivan", "Minnie", "Minotaur", "Miso Soup", "Mithril", "Mixer", "MMA", "Mocaccino", "Mozambique",
  "Backpack", "Modeling", "Coin", "Coins", "Mogadishu", "Mowgli", "Mill", "Moses", "Mojito", "Molar",
  "Moldova", "Soft", "Molecule", "Kid", "Sweatshirt", "Wet", "Sauce", "Monaco", "Monk", "Mongolia",
  "Monitor", "Unicycle", "Single-engine", "Monopoly", "Monorail", "Monster", "Mountain", "Monteiro Lobato", "Montenegro", "Montevideo",
  "Monument", "MOP", "Moral", "Strawberry", "Bat", "Moray Eel", "Lukewarm", "Walrus", "Death", "Dead",
  "Mosaic", "Moscow", "Mustard", "Monastery", "Motivation", "Motorcycle", "Motorcycle", "Engine", "Driver", "Motorola",
  "Mountain", "Mouse", "Mousse", "Furniture", "Mobile", "Mozart", "MP3", "MPB", "Muay", "Crutch",
  "Wonder Woman", "Multipurpose", "Mumbai", "Mummy", "Muscle", "Museum", "Moss", "Music", "Musical", "Mussolini",
  "In", "National", "Nothing", "Mothballs", "Suit", "Nairobi", "Namibia", "Girlfriend", "Boyfriend", "Boyfriend",
  "Napoleon", "Napoli", "Nostril", "Nose", "Naruto", "Spring", "Birth", "Swimming", "Christmas", "Natura",
  "Nautical", "Browser", "Ship", "Fog", "Toiletry Bag", "Necromancer", "Negotiator", "Black", "Negroni", "Nelson Mandela",
  "Neon", "Nepal", "Nerve", "Nervous", "Nestle", "Granddaughter", "Netflix", "Grandson", "Neuron", "Neutron",
  "Blizzard", "Snow", "Snow", "Fog", "Neymar", "Nicaragua", "Niger", "Nigeria", "Nigiri", "Nike",
  "Nikon", "Nintendo", "Nickel", "Nitrogen", "Nivea", "Level", "In", "Knockout", "Noah", "Night",
  "Bride", "Engagement", "Groom", "Disgust", "Noob", "Daughter-in-law", "Nori", "Norway", "Nostalgia", "Note",
  "Notary", "Laptop", "New York", "New Zealand", "New", "Walnut", "Little Knots", "Nubank", "Nape", "Never",
  "Nutritionist", "Cloud", "Nvidia", "Nylon", "Oasis", "Obama", "Obi-Wan", "Oboe", "Observation", "Observatory",
  "Obsidian", "Ocean", "Hollow", "Ochre", "Octagon", "Glasses", "Odin", "Hatred", "Workshop", "Ophthalmologist",
  "Ogre", "Oil", "Eye", "Olive", "Oman", "Shoulder", "Omo", "Jaguar", "Bus", "Bus",
  "Onyx", "Opaque", "Opal", "Opera", "Operational", "Operator", "Oppression", "Oral-B", "Orangutan", "Orb",
  "Orc", "Order", "Oregano", "Ear", "Organized", "Organ", "Pride", "Origami", "Orka Studio", "Orka Zoo",
  "Orchestra", "Orchid", "Dew", "OSB", "Oscar", "Oslo", "Bone", "Oyster", "Optimism", "Otolaryngologist",
  "Ottawa", "Hedgehog", "Gold", "Diamonds", "Roe", "Ovary", "Sheep", "Egg", "Oxygen", "Shovel",
  "Pac-Man", "Patience", "Packers", "Pacoca", "Pacu Fish", "Baker", "Stepfather", "Godfather", "Pager", "Pagode",
  "Father", "Panel", "Country", "Passion", "Palace", "Paladin", "Palette", "Clown", "Clown", "Palm",
  "Palmas", "Palmeiras", "Insole", "Eyelid", "Pamonha", "Panama", "Panasonic", "Pancreas", "Panda", "Tambourine",
  "Pot", "Panettone", "Panic", "Bakery", "Cloth", "Swamp", "Calf", "Bread", "Pope Francis", "Parrot",
  "Santa Claus", "Bogeyman", "Paper", "Cardboard", "Papua New Guinea", "Pakistan", "Screwdriver", "Screw", "Paraguay", "Cobblestone",
  "Paragliding", "Parachute", "Partner", "Partner", "Partnership", "Brown", "Relative", "Red Snapper", "Paris", "Park",
  "Easter", "Paste", "Pasture", "Pastor", "Paternity", "Goofy", "Scooter", "Skates", "Duck", "Donald Duck",
  "Patrick", "Patriots", "Stick", "Paulo Coelho", "Clubs", "Chopsticks", "Peacock", "Pave Dessert", "Paysandu", "Peace",
  "Foot", "Peach", "Piece", "Sin", "Pedagogue", "Stone", "Bricklayer", "Bricklayer", "Pedro Alvares Cabral", "Pegasus",
  "Chest", "Fish", "Fishmonger", "Pisces", "Skin", "Pele", "Pelvis", "Pen", "Penarol", "Comb",
  "Comb", "Cucumber", "Pepsi", "Small", "Beijing", "Pear", "Forgiveness", "Loser", "Perdigao", "Profile",
  "Perfume", "Puncher", "Drilling Rig", "Parchment", "Expert", "Leg", "Pearl", "Persian", "Insight", "Peru",
  "Van", "Wig", "Nightmare", "Heavy", "Neck", "Weight", "Researcher", "Peach", "Pessimism", "Shuttlecock",
  "Tanker", "Petunia", "Philips", "Sink", "Piano", "Top", "Woodpecker", "Arena", "Spicy", "Pickup Truck",
  "Pickaxe", "Picasso", "Pife Game", "Pyjamas", "Pikachu", "Pillar", "Pilot", "Pilsen", "Pepper", "Bell Pepper",
  "Piña", "Tweezers", "Brush", "Ping", "Penguin", "Pine Tree", "Pinscher", "Pintado Fish", "Painter", "Painting",
  "Kite", "Popcorn", "Picnic", "Piranha", "Arapaima", "Pool", "Track", "Pit", "Pitbull", "Pix",
  "Pixel", "Pizza", "Planer", "Planer", "Glider", "Planet", "Planetarium", "Plain", "Spreadsheet", "Planner",
  "Plant", "Plantation", "Platelet", "Plasma", "Plastic", "Platform", "Platinum", "Playmobil", "PlayStation", "Pluto",
  "Plutonium", "Pneumonia", "Powder", "Poor", "Potion", "Fanny Pack", "Well", "Point", "Poke", "Pole",
  "Thumb", "Policeman", "Polished", "Polyester", "Polisher", "Polo", "Poland", "Octopus", "Ointment", "Orchard",
  "Dove", "Pigeon", "Pomerania", "Poncho", "Pong", "Bridge", "Ponte Preta", "Poodle", "Pop", "Poker",
  "Basement", "Porcelain Tile", "Pig", "Pores", "Porous", "Porsche", "Door", "Portal", "Gate", "Port",
  "Porto Alegre", "Porto Velho", "Portugal", "Post", "Poseidon", "Position", "Post", "Post-it", "Station", "Potassium",
  "Pot", "Savings", "Inn", "Square", "Prada", "Prague", "Beach", "Clipboard", "Silver", "Shelf",
  "Plate", "Pleasure", "Building", "City Hall", "Nail", "Lazy", "Press", "Pressure", "Pressure", "Ham",
  "Black", "Suitor", "Black", "Pretoria", "Cousin", "Spring", "Cousin", "Princess Diana", "Privacy", "Toilet",
  "Pro", "Proactive", "Processor", "Procrastination", "Prosecutor", "Producer", "Prophecy", "Teacher", "Program", "Programming",
  "Programmer", "Projector", "Prosecutor", "Purpose", "Prostate", "Protection", "Protector", "Proton", "Province", "PSG",
  "Psychologist", "PSV", "Pudding", "Pug", "Lung", "Pullover", "Bracelet", "Pulse", "Puma", "Punch",
  "Wrist", "Pupil", "Putin", "PVC", "Court", "ATV", "Hip", "Painting", "Barracks", "Quarterback",
  "Bedroom", "Quartz", "That", "Break", "Broken", "Cheese", "Chin", "Kenya", "Hot", "Cherub",
  "Quest", "Chimera", "Chemistry", "Kimono", "Quindim", "Kyrgyzstan", "Quito", "R&B", "Frog", "French Toast",
  "Cracked", "Rational", "Radio", "Ragdoll", "Ray", "Queen Elizabeth", "Ray", "Anger", "Root", "Drain",
  "Ranch", "Rancor", "Ranger", "Rap", "Rapadura", "Fast", "Fox", "Racket", "Scraper", "Rat",
  "Rave", "Real", "Real Madrid", "Reactor", "Plaster", "Receptionist", "Receipt", "Recife", "Reco", "Reco",
  "Snippet", "Red Bull", "Red Sox", "Net", "Rein", "Redemption", "Reels", "Reincarnation", "Chorus", "Soda",
  "Tank Top", "Reggae", "Reggaeton", "Regal", "Region", "Ruler", "King", "King Arthur", "Kingdom", "United Kingdom",
  "Rejection", "Lightning", "Relativity", "Report", "Relic", "Watch", "Rowing", "Remorse", "Remover", "Renault",
  "Lace", "Renner", "Renewal", "Repellent", "Representative", "Czech Republic", "Cream Cheese", "Cold", "Resilience", "Resina",
  "Resistant", "Resolution", "Respect", "Responsibility", "Resentment", "Remain", "Restaurant", "Retina", "Retriever", "Backhoe",
  "Meetings", "New Year's Eve", "Coating", "Riachuelo", "Riyadh", "Rich", "Rigid", "Rihanna", "Kidney", "Rhinoceros",
  "River", "Rio Branco", "Rio de Janeiro", "Laugh", "Rhythm", "Rivalry", "River Plate", "RNA", "Snook Fish", "Robata",
  "Roberto Carlos", "Robot", "Rock", "Rock", "Round", "Wheels", "Rodizio", "Squeegee", "Highway", "Roadside",
  "Rolex", "Spring Roll", "Roll", "Rolls-Royce", "Roller", "Rome", "Romance", "Romania", "Romeo", "Ron",
  "Roosevelt", "Rose", "Rosary", "Rose Wine", "Face", "Roundabout", "Script", "Rottweiler", "Clothing", "Bathrobe",
  "Purple", "Royal", "Royal Enfield", "RPG", "Street", "Rwanda", "Ruby", "Ruble", "Rugby", "Rugose",
  "Rum", "Runas", "Rupee", "Rupture", "Russia", "Ryu", "Soap", "Wise", "Soap", "Balcony",
  "Bag", "Sadia", "Sapphire", "Sagittarius", "Sago", "Skirt", "Exit", "Salt", "Room", "Salad",
  "Salary", "Salty Snack", "Salmon", "Parsley", "Sausage", "Jump", "Salvador", "Salvador Dali", "Sage", "Fern",
  "Samba", "Samoa", "Samsung", "San Marino", "Sandal", "Sandwich Maker", "Accordion", "Blood", "Bleach", "Sanitary",
  "Santa Cruz", "Saint Lucia", "Santiago", "Saint", "Santos", "Sanctuary", "Saint", "San Francisco", "Saint John", "Sao Luis",
  "Sao Paulo", "Sao Tome and Principe", "Tap Dancing", "Ballet Flat", "Shoe", "Shoes", "Frog", "Sake", "Sardine", "Sergeant",
  "Serge", "Sashimi", "Sasuke", "Satan", "Satellite", "Satire", "Satisfaction", "Saudade", "Healthy", "Sauron",
  "Savannas", "Saxophone", "Scania", "Schumacher", "Scooby-Doo", "Scooter", "Scorpion", "Scorsese", "Script", "Seara",
  "Drought", "Dryer", "Dry", "Silk", "Sedan", "Follower", "Security", "Saddle", "Sealer", "German Team",
  "Argentine Team", "Brazilian Team", "French Team", "Italian Team", "Stamps", "Jungle", "Seed", "Sempiternal", "Always", "Senegal",
  "Password", "Senna", "Sensor", "Sense", "Separation", "Septum", "Seraphim", "Mermaid", "Serendipity", "Serenity",
  "Serpent", "Saw", "Mountain Range", "Sierra Leone", "Handsaw", "Sertanejo", "Serbia", "Service", "Server", "Set",
  "Seoul", "Sevilla", "Shakespeare", "Shakira", "Shampoo", "Sherlock Holmes", "Shih", "Shimeji", "Shiitake", "Shopping Mall",
  "Shorts", "Show", "Soy Sauce", "Siamese", "Siberian", "Siphon", "Secrecy", "Silence", "Silicon", "Silo",
  "Silvio Santos", "Simulation", "Sinagoga", "Signal", "Sinapse", "Sincere", "Singapore", "Crab", "Syria", "Wisdom Tooth",
  "System", "Sitar", "Site", "Small Farm", "Skateboard", "Slide", "Slime", "Smartphone", "Smartwatch", "Snowboarding",
  "Two-story House", "Eyebrow", "Overcoat", "Niece", "Nephew", "Social", "Partner", "Rescuer", "Sodium", "Sofa",
  "Softball", "Software", "Mother-in-law", "Father-in-law", "Soy", "Sun", "Sole", "Solar", "Welder", "Welder",
  "Loneliness", "Solidarity", "Solid", "Ground", "Sound", "Somalia", "Shadow", "Shadows", "Sommelier", "Dream",
  "Sonic", "Sony", "Luck", "Ice Cream", "Attic", "Soul", "Armpit", "Spam", "Spaniel", "Sphynx",
  "Spoiler", "Sport", "Sporting", "Spotify", "Sri Lanka", "Stalin", "Stan Lee", "Steve Jobs", "Steven Spielberg", "Sticker",
  "Stop", "Story", "Stout", "Streamer", "Streaming", "Swaziland", "Sub-Zero", "Submarine", "Suburb", "Juice",
  "Succulent", "Sudan", "Sudare", "Sudoku", "Sweden", "Sweater", "Switzerland", "Suite", "Dirty", "Sulfite Paper",
  "Swim Briefs", "Superman", "Supernova", "Surfing", "Meerkat", "Suriname", "Surprise", "Sushi", "Suspended", "Suspense",
  "Meringue", "Fright", "Bra", "SUV", "Suva", "Suzuki", "Sydney", "Tablet", "Board", "Board",
  "Club", "Taekwondo", "Taiga", "Thailand", "Tails", "Mullet Fish", "Taipei", "Taiwan", "Tajikistan", "Talc",
  "Chisel", "Cutlery", "Talisman", "Tambaqui Fish", "Drum", "Tango", "Tank", "Tanzania", "Rug", "Tapioca",
  "Tarantino", "Tare Sauce", "Tarot", "Turtle", "Tarzan", "Tatami", "Tavern", "Taxi Driver", "Theater", "Techno",
  "Keyboard", "Technique", "Technician", "Technology", "Boredom", "Tehran", "Stubborn", "Screen", "Cable Car", "Telephone",
  "Telescope", "Television", "Tile", "Temaki", "Fear", "Storm", "Temple", "Time", "Tempura", "Tendon",
  "Tennis", "Sneakers", "Tension", "Teppan", "Tequila", "Therapist", "Terere", "Teresina", "Teriyaki", "Terminal",
  "Suit", "Earth", "Terrace", "Terreiro", "Earthquake", "Terror", "Tesla", "Scissors", "Treasurer", "Treasure",
  "Forehead", "Witness", "Text", "Badger", "Thai", "Thanos", "Thor", "Aunt", "Tibia", "Tie",
  "Tiger", "Brick", "TikTok", "Tilapia", "Shyness", "Shy", "East Timor", "Eardrum", "Ink", "Inkwell",
  "Uncle", "Tiradentes", "Thyroid", "Titan", "Titanium", "Towell", "Burrow", "Tofu", "Togo", "Tolerance",
  "Tone", "Socket", "Tomato", "Tommy Hilfiger", "Tonga", "Topaz", "Tokyo", "Torah", "Thorax", "Torsion",
  "Tornado", "Tap", "Turner", "Lathe", "Ankle", "Toaster", "Tower", "Pork Rind", "Pie", "Cough",
  "Totality", "Tottenham", "Cap", "Touchdown", "Bull", "Toyota", "Tragedy", "Traitor", "Trailer", "Trampoline",
  "Locked", "Trance", "Ocean Liner", "Protractor", "Transformer", "Translucent", "Transparent", "Trap", "Trapeze", "Trapeze Artist",
  "Trachea", "Tractor", "Goalpost", "Pillow", "Train", "Tape Measure", "Trend", "Sled", "Darkness", "Clover",
  "Court", "Tricycle", "Knitting", "Wheat", "Trail", "Trinidad and Tobago", "Trypophobia", "Tripoli", "Sad", "Sadness",
  "Triumph", "Troll", "Trombone", "Horn", "Trumpet", "Trunk", "Throne", "Tropeiro", "Thunder", "Truco",
  "Truffle", "Trump", "Trick", "Trout", "Tsunami", "Tuba", "Shark", "Everything", "Typhoon", "Tulle",
  "Tulip", "Tomb", "Tundra", "Tunnel", "Tunisia", "Turbine", "Turkmenistan", "Shift", "Turquoise", "Turkey",
  "Guardianship", "Tutor", "Tuvalu", "Twitter", "Tyson", "Tzu", "Uber", "Ukraine", "Udon", "UFC",
  "Uganda", "Ukulele", "Ulcer", "Ulna", "One", "Navel", "Moistened", "Humerus", "Humid", "Nail",
  "Union", "Unicorn", "Uniform", "University", "Uno", "Upload", "Uramaki", "Uranium", "Urbanist", "URL",
  "Bear", "Uruguay", "Used", "USB", "Uterus", "Utility", "Grape", "Uzbekistan", "Cow", "Vaccine",
  "Wagon", "Vanity", "Valley", "Valencia", "Jack", "Values", "Waltz", "Valve", "Vampire", "Van",
  "Van Gogh", "Vanuatu", "Veranda", "Wand", "Warsaw", "Vasco", "Vase", "Broom", "Vatican", "Leak",
  "Empty", "Deer", "Vedas", "Vegeta", "Vein", "Veja", "Sailboat", "Old", "Velvet", "Winner",
  "Seller", "Venezuela", "Fan", "Wind", "Fan", "Womb", "Ventricle", "Truth", "Green", "Rebar",
  "Shame", "Red", "Red", "Varnish", "Versace", "Verse", "Gallbladder", "Dress", "Veterinarian", "Viaduct",
  "Travel", "Vehicle", "Vibration", "Life", "Psychic", "VCR", "Video Game", "Glass", "Scallop", "Vienna",
  "Vietnam", "Beam", "Village", "Vila Nova", "Vinegar", "Wine", "Vinyl", "Viola", "Acoustic Guitar", "Violet",
  "Violin", "Cello", "Vira", "Viral", "Virgo", "Groin", "Virtual", "Virtue", "Virus", "Visa",
  "Viscose", "Victory", "Live", "Nursery", "Alive", "Neighbor", "Vodka", "Voldemort", "Volleyball", "Volkswagen",
  "Volume", "Volvo", "Clam", "Will", "Vortex", "Voice", "VR", "Volcano", "Figure", "Walkman",
  "Walt Disney", "War", "Warren Buffett", "Warriors", "Wasabi", "Washington", "Watson", "Weiss", "Wellington", "Whiskey",
  "Wi-Fi", "Williams", "Windsurfing", "Wok", "Chess", "Shanghai", "Syrup", "Xbox", "Xiaomi", "Cup",
  "Xylophone", "Xuxa", "Yakisoba", "Yamaha", "Yankees", "Yoda", "Yoga", "Yorkshire", "YouTube", "Youtuber",
  "Yuan", "Zambia", "Zara", "Zebra", "Zelda", "Zeus", "Zimbabwe", "Zinc", "Zipper", "Zoo", "Zumba", "Zombie",
  "Tailor", "Alchemist", "Altruism", "Alluvium", "Hourglass", "Anticyclone", "Fishhook", "Sideboard", "Beekeeper", "Sconce",
  "Archaeologist", "Arrogance", "Atoll", "Bay", "Barrier", "Basalt", "Benevolence", "Librarian", "Biologist", "Scalpel",
  "Nozzle", "Bodega", "Bravery", "Compass", "Canyon", "Flowerbed", "Cascade", "Candlestick", "Turnstile", "Censor",
  "Rattle", "Clapperboard", "Cleric", "Greed", "Commissioner", "Choreographer", "Summit", "Gift", "Thimble", "Thaw",
  "Taster", "Plunger", "Contempt", "Tuning Fork", "Dilemma", "Diplomat", "Hinge", "Playwright", "Dune", "Ecologist",
  "Eloquence", "Commitment", "Enigma", "Cove", "Escarpment", "Writer", "Emery", "Statistician", "Steppe", "Case",
  "Stirrup", "Cliff", "Fascination", "Cleft", "Blacksmith", "Fervor", "Costume Designer", "Harpoon", "Bellows", "Forensic",
  "Mouth of River", "Frenzy", "Funnel", "Spindle", "Greed", "Prospector", "Geyser", "Glacier", "Geologist", "Dripper",
  "Gramophone", "Large Cave", "Gluttony", "Propeller", "Hesitation", "Spotlight", "Honor", "Horticulturist", "Igapo Forest", "Igarape",
  "Illusionist", "Impetus", "Immunologist", "Censer", "Inertia", "Yogurt Maker", "Irony", "Lighter", "Lab Coat", "Jar",
  "Deposit", "Newsagent", "Journalist", "Jubilation", "Reed", "Joint", "Seal", "Mud", "Lantern", "Lasciviousness",
  "Auctioneer", "Silt", "Light", "Spyglass", "Luthier", "Blowtorch", "Mangrove Swamp", "Crank", "Sea Air", "Melancholy",
  "Messenger", "Diver", "Mine", "Modesty", "Milliner", "Gag", "Hookah", "Razor", "Mist", "Ball of Yarn",
  "Loathing", "Oratory", "Goldsmith", "Ombudsman", "High Seas", "Pendulum", "Peninsula", "Piety", "Plateau", "Poet",
  "Plumb Line", "Brace", "Modesty", "Kerosene", "Keel", "Quilombola", "Chemist", "Rancidity", "Grindstone", "Watchmaker",
  "Renunciation", "Large Stream", "Pulley", "Router", "Screenwriter", "Sarcasm", "Syringe", "Locksmith", "Backlands", "Silicate",
  "Bell", "Haughtiness", "Soldier", "Driller", "Quietude", "Support", "Weaver", "Topographer", "Torpor", "Translator",
  "Latch", "Crusher", "Tube", "Peat", "Boastfulness", "Utopia", "Sailor", "Vigor", "Revenge", "Steering Wheel", "Zeal",
  "Nest", "Cigarette", "Cigar", "Padlock"
];